"""Sinh MOI hinh, MOI bang va MOI macro so cua bai tu code/results/.

⛔ LUAT MOT NGUON: khong con so nao duoc go tay vao paper/. Quy tac doc CSV nam o
code/analysis/rules.py, dung chung voi analysis/make_tables.py.

Vong sua 1 (review 12/09/2026) them: p-value sign test va Wilcoxon tung o, hieu chinh Holm,
khoang tin cay bootstrap, nguoi dan theo trung binh ben moi phan quyet, bang do nhay nguong,
bang doi thuoc MAE<->AURC, thanh phan o bi loai, thanh phan o vuot 2% o shell lon, GCN co sd va n,
PPR/SGC khi co du lieu, luat 5 tren MOI nhanh co mat trong luoi 1000 epoch.
Chay:  python3 figures/make_figures.py
"""
import csv
import io
import json
import os
import re
import sys
from math import erf, sqrt

import numpy as np
import matplotlib as mpl

mpl.use("Agg")
import matplotlib.pyplot as plt                                    # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
RES = os.path.join(ROOT, "code", "results")
OUTD = os.path.join(HERE, "out")
os.makedirs(OUTD, exist_ok=True)
sys.path.insert(0, os.path.join(ROOT, "code"))
from analysis import rules as R                                    # noqa: E402
from src.scale import SHELLS as _SH, PPR_ALPHA, PPR_K, SGC_K       # noqa: E402

mpl.rcParams.update({
    "font.family": "serif", "font.serif": ["DejaVu Serif"],
    "mathtext.fontset": "dejavuserif", "font.size": 9,
    "axes.titlesize": 9, "axes.labelsize": 9, "legend.fontsize": 8,
    "xtick.labelsize": 8, "ytick.labelsize": 8,
    "axes.linewidth": 0.6, "axes.spines.top": False, "axes.spines.right": False,
    "xtick.direction": "in", "ytick.direction": "in",
    "lines.linewidth": 1.1, "lines.markersize": 4.0, "legend.frameon": False,
    "figure.dpi": 130, "pdf.fonttype": 42, "ps.fonttype": 42,
})
C = {"gcn": "#555555", "heat": "#D55E00", "qw": "#0072B2", "ppr": "#009E73", "sgc": "#CC79A7", "const": "#009E73"}
MK = {"gcn": "s", "heat": "o", "qw": "^", "ppr": "D", "sgc": "v"}
LS = {"gcn": ":", "heat": "-", "qw": "--", "ppr": "-.", "sgc": ":"}
LBL = {"gcn": "GCN (local)", "heat": r"heat $e^{-tL}$", "qw": r"walk $|e^{-itL}|^2$", "ppr": "PPR", "sgc": "SGC"}
OPN = {"gcn": "GCN", "heat": "heat", "qw": "walk", "ppr": "PPR", "sgc": "SGC"}
# ⛔ [preprint,11pt,3p] elsarticle: \textwidth = 468 pt = 6,48 in, DO bang \typeout trong main.tex.
W_WIDE, W_HALF = 6.48, 4.00
SHELLS, NN = R.SHELLS, R.NN
SHNAME = {"s264": "Small", "s1584": "ShellOne", "s3168": "Double", "s4400": "Large"}
CFGS = ["h16l3", "h32l4"]
CFGNAME = {"h16l3": "Released", "h32l4": "Submitted"}
ARMS = ["relu/t0=0.5", "relu/t0=2", "softplus/t0=0.5", "softplus/t0=2"]
NUM = {}


def M(name, value):
    key = re.sub(r"[^A-Za-z]", "", name)
    assert key not in NUM or NUM[key] == value, "macro %s bi dat hai lan khac gia tri" % key
    NUM[key] = value
    return value


def save(fig, name, target_w=W_WIDE):
    path_pdf = os.path.join(OUTD, "%s.pdf" % name)
    got = None
    for _ in range(12):
        fig.savefig(path_pdf, bbox_inches="tight")
        mm = re.findall(rb"/MediaBox\s*\[([^\]]*)\]", open(path_pdf, "rb").read())
        if not mm:
            break
        x0, y0, x1, y1 = [float(v) for v in mm[0].split()]
        got = (x1 - x0) / 72.0
        if abs(got - target_w) < 0.005:
            break
        w, h = fig.get_size_inches()
        fig.set_size_inches(max(w + (target_w - got), 1.5), h)
    fig.savefig(os.path.join(OUTD, "%s.png" % name), bbox_inches="tight", dpi=200)
    plt.close(fig)
    print("     %-18s %.2f in" % (name, got or -1))


def pm(st, op, d=3):
    return ("%%.%df $\\pm$ %%.%df (%%d)" % (d, d)) % (st[op][0], st[op][1], st[op][2]) if op in st else "---"


def fp(p):
    return "---" if p != p else ("$<$0.001" if p < 0.001 else "%.3f" % p)


def fm(x):
    return "---" if x != x else "%.3f" % x


WIDE = {"tab3-s264-200ep.tex", "tab2-grid3.tex", "tab5-aurc.tex", "tab-swap.tex", "tab2b-grid3-inference.tex", "tab5b-aurc-inference.tex", "tab-fixed.tex",
        "tab-ladder.tex", "tab-seam.tex", "tab-seam-grid.tex", "tab-seam-grid-inference.tex", "tab-pooled.tex", "tab-pooled-aurc.tex", "tab-seam-pooled.tex", "tab-seam-pooled-aurc.tex"}


TIGHT = {"tab-seam.tex", "tab-power.tex"}


def tabfile(name, lines):
    body = "\n".join(lines)
    if name in TIGHT:                      # bang 10-11 cot
        body = "{\\scriptsize\\setlength{\\tabcolsep}{2.5pt}\n" + body + "\n}"
    elif name in WIDE:                     # bang 8-9 cot: co chu \\footnotesize + tabcolsep 3.5pt de vua khung 6,48 in
        body = "{\\footnotesize\\setlength{\\tabcolsep}{3.5pt}\n" + body + "\n}"
    io.open(os.path.join(OUTD, name), "w").write("% GENERATED by figures/make_figures.py\n" + body + "\n")


def arm_label(a):
    return a.replace("/t0=", ", $t_0{=}$")


def mr(cfg, k, n):
    return ("\\multirow{%d}{*}{%s}" % (n, CFGNAME[cfg].lower())) if k == 0 else ""


# ================================================================ du lieu
g12 = R.load([os.path.join(RES, "grid12", "scale_*.csv")])
g3 = R.load([os.path.join(RES, "grid3", "scale_h32l4e1000_*.csv")])
ARMS3 = sorted({r["arm"] for r in g3 if r["op"] in ("heat", "qw")}, key=lambda a: ARMS.index(a) if a in ARMS else 9)
# review vong 2: hang so far-node cho moi o (luat 1); cac CSV cu khong co cot nay -> tra tu fields.py
_CA = json.load(open(os.path.join(RES, "const_aurc.json")))
for r in g12 + g3:
    if r["const_aurc"] != r["const_aurc"] and r["shell"] in _CA.get(r["task"], {}):
        r["const_aurc"] = _CA[r["task"]][r["shell"]][str(r["seed"])]
print("  grid12: %d hang, %d benh ly · grid3: %d hang, %d benh ly · nhanh luoi 3: %s"
      % (len(g12), sum(r["pathology"] for r in g12), len(g3), sum(r["pathology"] for r in g3), ARMS3))
CORE = ("gcn", "heat", "qw")
M("numGridTwelveRuns", sum(1 for r in g12 if r["op"] in CORE))
M("numGridTwelvePathology", sum(r["pathology"] for r in g12 if r["op"] in CORE))
M("numGridTwelvePlateau", sum(r["plateau"] for r in g12 if r["op"] in CORE))
M("numGridThreeRuns", sum(1 for r in g3 if r["op"] in CORE))
M("numGridThreePathology", sum(r["pathology"] for r in g3 if r["op"] in CORE))
M("numGridThreePathologyPct", round(100.0 * NUM["numGridThreePathology"] / max(NUM["numGridThreeRuns"], 1), 1))
M("numGridThreeArms", len(ARMS3))
M("numFixedRunsTwelve", sum(1 for r in g12 if r["op"] in ("ppr", "sgc"))); M("numFixedRunsThree", sum(1 for r in g3 if r["op"] in ("ppr", "sgc")))
M("numTotalRuns", len(g12) + len(g3))
M("numFixedPathology", sum(r["pathology"] for r in g12 + g3 if r["op"] in ("ppr", "sgc")))
HAS_FIXED = any(r["op"] in ("ppr", "sgc") for r in g12 + g3)
M("numPprAlpha", "%g" % PPR_ALPHA); M("numPprK", PPR_K); M("numSgcK", SGC_K)

# ================================================================ bang shell (tu ma)
T = ["\\begin{tabular}{@{}rrrrrl@{}}\n\\toprule\nsatellites & planes & per plane & incl.\\ ($^{\\circ}$) & alt.\\ (km) & note \\\\\n\\midrule"]
NOTE = {"s264": "main scale of the preliminary version", "s1584": "Starlink shell-1 geometry~\\cite{starlink}",
        "s3168": "scale-up, synthetic", "s4400": "scale-up, synthetic"}
for k in SHELLS:
    tot, planes, f, inc, alt, _ = _SH[k]
    T.append("%d & %d & %d & %g & %g & %s \\\\" % (tot, planes, tot // planes, inc, alt, NOTE[k]))
T.append("\\bottomrule\n\\end{tabular}"); tabfile("tab0-shells.tex", T)

# ================================================================ hien vat ban so bo, chi phi CPU, kiem cache
PRE = os.path.join(ROOT, "code", "results-as-submitted-2026-06-28")
pre = {r["op"]: r for r in csv.DictReader(open(os.path.join(PRE, "exp_e_shell1.csv")))}
M("numPrelimWalkMAE", "%.3f" % float(pre["qw"]["mae_mean"])); M("numPrelimHeatMAE", "%.3f" % float(pre["heat"]["mae_mean"]))
M("numPrelimParams", int(float(pre["qw"]["params"])))
M("numPrelimSeeds", len(list(csv.DictReader(open(os.path.join(PRE, "exp_e_shell1_perseed.csv"))))) // 3)
M("numReleasedParams", int(next(r for r in g12 if r["cfg"] == "h16l3")["params"]))
M("numSubmittedParams", int(next(r for r in g12 if r["cfg"] == "h32l4")["params"]))
cpu = json.load(open(os.path.join(RES, "cpu-smoke.json")))
M("numCpuSecsLarge", int(round(max(cpu["s4400_cpu_secs"].values()))))
M("numCacheIdenticalDigits", cpu["cache_identity_check"]["identical_digits"])

# ================================================================ LUOI 1-2: san
fig, axes = plt.subplots(2, 2, figsize=(W_WIDE, 5.0), sharey=True, sharex=True)
n_floor = n_rank = 0
for r_, task in enumerate(("hops", "delay")):
    for c_, cfg in enumerate(CFGS):
        ax = axes[r_, c_]
        for ai, arm in enumerate(ARMS):
            ys = []
            for sh in SHELLS:
                st, cm, gain, vd, ld = R.summarise(R.cell(g12, task, sh, arm, cfg, 200))
                ys.append(100 * gain)
                if sh != "s264" and task == "hops":
                    n_floor += vd == "floor"; n_rank += vd != "floor"
            ax.plot(range(4), ys, marker="osd^"[ai], ls=["-", "--", "-", "--"][ai],
                    color=["#D55E00", "#D55E00", "#0072B2", "#0072B2"][ai], label=arm.replace("/t0=", ", $t_0$="))
        ax.axhline(100 * R.FLOOR_GAIN, color="#009E73", lw=0.8, ls=":")
        ax.set_xticks(range(4)); ax.set_xticklabels(["264", "1584", "3168", "4400"])
        if r_ == 0:
            ax.set_title({"h16l3": "released: width 16, 3 layers", "h32l4": "submitted: width 32, 4 layers"}[cfg], fontsize=8)
        if r_ == 1:
            ax.set_xlabel("satellites in shell")
        if c_ == 0:
            ax.set_ylabel("%s field\ngain over constant (%%)" % task)
axes[0, 0].legend(loc="upper right", fontsize=7)
fig.subplots_adjust(hspace=0.15, wspace=0.08)
save(fig, "fig1-floor")
M("numFloorCellsLarge", n_floor); M("numRankableCellsLarge", n_rank)
for cfg in CFGS:
    for task in ("hops", "delay"):
        g264 = [R.summarise(R.cell(g12, task, "s264", a, cfg, 200))[2] for a in ARMS]
        M("numGain" + task.capitalize() + "SmallMin" + CFGNAME[cfg], round(100 * min(g264), 1))
        M("numGain" + task.capitalize() + "SmallMax" + CFGNAME[cfg], round(100 * max(g264), 1))
    gbig = [R.summarise(R.cell(g12, t, s, a, cfg, 200))[2] for a in ARMS for s in SHELLS[1:] for t in ("hops", "delay")]
    M("numGainLargeMax" + CFGNAME[cfg], round(100 * max(gbig), 1))
M("numGainLargeMax", max(NUM["numGainLargeMaxReleased"], NUM["numGainLargeMaxSubmitted"]))
spread = []
for cfg in CFGS:
    for arm in ARMS:
        for task in ("hops", "delay"):
            st = R.summarise(R.cell(g12, task, "s4400", arm, cfg, 200))[0]
            mus = [v[0] for v in st.values()]
            if len(mus) == 3: spread.append(max(mus) - min(mus))
M("numLargeSpreadMax", "%.3f" % max(spread))
big_valid = [r for r in g12 if not r["pathology"] and r["shell"] != "s264" and r["op"] in CORE]
M("numGridTwelveLargeRuns", len(big_valid))
above = [r for r in big_valid if r["mae"] < 0.98 * r["const_mae"]]
M("numGridTwelveAtFloorLarge", len(big_valid) - len(above)); M("numGridTwelveAbove", len(above))
T = ["\\begin{tabular}{@{}llrrrr@{}}\n\\toprule\ncapacity & operator & 1584 & 3168 & 4400 & all \\\\\n\\midrule"]
big_valid_fx = [r for r in g12 if not r["pathology"] and r["shell"] != "s264" and r["op"] in ("ppr", "sgc")]
above_fx = [r for r in big_valid_fx if r["mae"] < 0.98 * r["const_mae"]]
for cfg in CFGS:
    ops_ = CORE + (("ppr", "sgc") if cfg == "h32l4" else ())
    for k, op in enumerate(ops_):
        src_ = above if op in CORE else above_fx
        row = [sum(1 for r in src_ if r["cfg"] == cfg and r["op"] == op and r["shell"] == sh) for sh in SHELLS[1:]]
        T.append("%s & %s & %s & %d \\\\" % (mr(cfg, k, len(ops_)), OPN[op], " & ".join(str(x) for x in row), sum(row)))
    if cfg == CFGS[0]:
        T.append("\\midrule")
M("numGridTwelveLargeRunsFixed", len(big_valid_fx)); M("numGridTwelveAboveFixed", len(above_fx))
T.append("\\bottomrule\n\\end{tabular}"); tabfile("tab-above.tex", T)
M("numAboveWalkShellOne", sum(1 for r in above if r["op"] == "qw" and r["shell"] == "s1584"))
M("numAboveHeatShellOne", sum(1 for r in above if r["op"] == "heat" and r["shell"] == "s1584"))
M("numAboveMaxGainPct", round(100 * max((r["const_mae"] - r["mae"]) / r["const_mae"] for r in above), 1))

T = ["\\begin{tabular}{@{}llrrrrcrrrr@{}}\n\\toprule\n& & \\multicolumn{4}{c}{hop field} & & \\multicolumn{4}{c}{delay field} \\\\\n\\cmidrule{3-6}\\cmidrule{8-11}\ncapacity & $t$ arm & 264 & 1584 & 3168 & 4400 & & 264 & 1584 & 3168 & 4400 \\\\\n\\midrule"]
for cfg in CFGS:
    for k, arm in enumerate(ARMS):
        parts = []
        for task in ("hops", "delay"):
            cells = [R.summarise(R.cell(g12, task, sh, arm, cfg, 200)) for sh in SHELLS]
            parts.append(" & ".join(("%.1f" % (100 * g)) + ("" if vd != "floor" else "$^{\\dagger}$") for (_, _, g, vd, _) in cells))
        T.append("%s & %s & %s & & %s \\\\" % (mr(cfg, k, 4), arm_label(arm), parts[0], parts[1]))
    if cfg == CFGS[0]:
        T.append("\\midrule")
T.append("\\bottomrule\n\\end{tabular}"); tabfile("tab1-floor.tex", T)

# ================================================================ s264 o 200 epoch
fig, axes = plt.subplots(1, 4, figsize=(W_WIDE, 2.8), sharey=True)
verd = {}
for cfg in CFGS:
    for arm in ARMS:
        verd[(cfg, arm)] = R.summarise(R.cell(g12, "hops", "s264", arm, cfg, 200))[3]
for ax, arm in zip(axes, ARMS):
    c = R.cell(g12, "hops", "s264", arm, "h32l4", 200)
    st, cm, gain, vd, ld = R.summarise(c)
    for xi, op in enumerate(CORE):
        ys = [r["mae"] for r in c.get(op, {}).values()]
        ax.scatter(np.full(len(ys), xi) + np.random.default_rng(0).uniform(-0.12, 0.12, len(ys)), ys, s=12, color=C[op], marker=MK[op], alpha=0.8)
        ax.hlines(np.mean(ys), xi - 0.25, xi + 0.25, color=C[op], lw=1.4)
    ax.axhline(cm, color=C["const"], lw=0.8, ls=":")
    ax.set_xticks([0, 1, 2]); ax.set_xticklabels(["GCN", "heat", "walk"])
    ax.set_title(arm.replace("/t0=", "\n$t_0$=") + "\nverdict: " + vd, fontsize=8)
axes[0].set_ylabel("MAE, 264 satellites")
save(fig, "fig2-s264-arms")
M("numSTwoSixFourVerdictsSubmitted", " / ".join(verd[("h32l4", a)] for a in ARMS))
M("numSTwoSixFourVerdictsReleased", " / ".join(verd[("h16l3", a)] for a in ARMS))
vds = list(verd.values())
M("numSTwoSixFourHeatWins", sum(v == "heat" for v in vds)); M("numSTwoSixFourWalkWins", sum(v == "walk" for v in vds))
M("numSTwoSixFourTies", sum(v == "tie" for v in vds)); M("numSTwoSixFourCells", len(vds))
M("numSTwoSixFourConst", "%.3f" % R.summarise(R.cell(g12, "hops", "s264", ARMS[0], "h32l4", 200))[1])
M("numGcnSdSmall", "%.3f" % max(R.summarise(R.cell(g12, "hops", "s264", a, cfg, 200))[0]["gcn"][1] for cfg in CFGS for a in ARMS))
T = ["\\begin{tabular}{@{}lllllcrl@{}}\n\\toprule\ncapacity & $t$ arm & GCN & heat & walk & heat:walk & $p_{\\mathrm{sign}}$ & verdict \\\\\n\\midrule"]
esc = {}; walk_win_p = None
for cfg in CFGS:
    for k, arm in enumerate(ARMS):
        c = R.cell(g12, "hops", "s264", arm, cfg, 200); st, cm, gain, vd, ld = R.summarise(c); ps = R.paired_stats(c)
        T.append("%s & %s & %.3f (%d) & %s & %s & %d:%d & %s & %s \\\\" % (mr(cfg, k, 4), arm_label(arm), st["gcn"][0], st["gcn"][2], pm(st, "heat"), pm(st, "qw"), ps["wins_a"], ps["wins_b"], fp(ps["p_sign"]), vd))
        if vd == "walk":
            walk_win_p = ps["p_sign"]
        for op in ("heat", "qw"):
            rs = list(c.get(op, {}).values()); esc[(cfg, arm, op)] = (sum(r["escaped"] for r in rs), len(rs))
    if cfg == CFGS[0]:
        T.append("\\midrule")
T.append("\\bottomrule\n\\end{tabular}"); tabfile("tab3-s264-200ep.tex", T)
M("numSTwoSixFourWalkWinP", fp(walk_win_p) if walk_win_p is not None else "---")
T = ["\\begin{tabular}{@{}llcc@{}}\n\\toprule\ncapacity & $t$ arm & heat: escaped/valid & walk: escaped/valid \\\\\n\\midrule"]
tot_e = {"heat": [0, 0], "qw": [0, 0]}
for cfg in CFGS:
    for k, arm in enumerate(ARMS):
        e_h, n_h = esc[(cfg, arm, "heat")]; e_q, n_q = esc[(cfg, arm, "qw")]
        tot_e["heat"][0] += e_h; tot_e["heat"][1] += n_h; tot_e["qw"][0] += e_q; tot_e["qw"][1] += n_q
        T.append("%s & %s & %d/%d & %d/%d \\\\" % (mr(cfg, k, 4), arm_label(arm), e_h, n_h, e_q, n_q))
    if cfg == CFGS[0]:
        T.append("\\midrule")
T.append("\\bottomrule\n\\end{tabular}"); tabfile("tab4-escape.tex", T)
M("numEscapeHeat", "%d/%d" % tuple(tot_e["heat"])); M("numEscapeWalk", "%d/%d" % tuple(tot_e["qw"]))
M("numEscapeHeatPct", round(100.0 * tot_e["heat"][0] / tot_e["heat"][1])); M("numEscapeWalkPct", round(100.0 * tot_e["qw"][0] / tot_e["qw"][1]))
p1, n1 = tot_e["heat"]; p2, n2 = tot_e["qw"]; pp = (p1 + p2) / (n1 + n2)
z = ((p1 / n1) - (p2 / n2)) / np.sqrt(pp * (1 - pp) * (1 / n1 + 1 / n2))
M("numEscapePz", "%.2f" % (2 * (1 - 0.5 * (1 + erf(abs(z) / sqrt(2))))))

# ================================================================ t hoc duoc
def tl_panel(ax, rows, epochs, shells):
    for op in ("heat", "qw"):
        tl = []
        for sh in shells:
            c = R.cell(rows, "hops", sh, "softplus/t0=0.5", "h32l4", epochs)
            ts = np.array([r["t_learned"] for r in c.get(op, {}).values()])
            tl.append(ts.mean(0) if len(ts) else np.full(4, np.nan))
        tl = np.array(tl)
        for l in range(tl.shape[1]):
            ax.plot(range(len(shells)), tl[:, l], color=C[op], ls=LS[op], marker=MK[op], ms=3, alpha=0.35 + 0.65 * l / 3, label=LBL[op] if l == 0 else None)
    ax.set_xticks(range(len(shells))); ax.set_xticklabels([str(NN[s]) for s in shells])
    ax.set_xlabel("satellites in shell"); ax.set_title("%d epochs" % epochs, fontsize=8)

fig, axes = plt.subplots(1, 2, figsize=(W_WIDE, 2.9))
tl_panel(axes[0], g12, 200, SHELLS)
if g3:
    tl_panel(axes[1], g3, 1000, SHELLS[:3])
axes[0].set_ylabel("learned $t$ per layer"); axes[0].legend(fontsize=7)
save(fig, "fig3-t-learned")

# ================================================================ LUOI 3: 1000 epoch
if g3:
    T = ["\\begin{tabular}{@{}lrrrrcrrrr@{}}\n\\toprule\n& \\multicolumn{4}{c}{heat $e^{-t\\Lap}$} & & \\multicolumn{4}{c}{walk $|e^{-it\\Lap}|^{2}$} \\\\\n\\cmidrule{2-5}\\cmidrule{7-10}\n$N$ & $t_1$ & $t_2$ & $t_3$ & $t_4$ & & $t_1$ & $t_2$ & $t_3$ & $t_4$ \\\\\n\\midrule"]
    for sh in SHELLS[:3]:
        row = []
        for op in ("heat", "qw"):
            c = R.cell(g3, "hops", sh, "softplus/t0=0.5", "h32l4", 1000)
            ts = np.array([r["t_learned"] for r in c.get(op, {}).values()])
            row.append(" & ".join("%.1f" % v for v in ts.mean(0)))
            M("numTlayerOne" + SHNAME[sh] + ("Heat" if op == "heat" else "Walk"), "%.1f" % ts.mean(0)[0])
        T.append("%d & %s & & %s \\\\" % (NN[sh], row[0], row[1]))
    T.append("\\bottomrule\n\\end{tabular}"); tabfile("tab7-tlearned.tex", T)

    fig, axes = plt.subplots(1, 2, figsize=(W_WIDE, 3.2), sharey=True)
    X = [0, 1, 2]
    arms_plot = [a for a in ARMS3 if a.endswith("0.5")]
    for ax, task in zip(axes, ("hops", "delay")):
        for op in CORE:
            for ai, arm in enumerate(arms_plot):
                mu, sd = [], []
                for sh in SHELLS[:3]:
                    st, cm, gain, vd, ld = R.summarise(R.cell(g3, task, sh, arm, "h32l4", 1000))
                    mu.append(st.get(op, (np.nan,))[0]); sd.append(st.get(op, (0, 0))[1])
                off = (-0.06 if ai == 0 else 0.06) + {"gcn": -0.12, "heat": 0.0, "qw": 0.12}[op]
                ax.errorbar([x + off for x in X], mu, yerr=sd, color=C[op], marker=MK[op], ls=["-", "--"][ai], capsize=1.5, lw=0.9, ms=3.2, elinewidth=0.6, label=(LBL[op] + ", " + arm.split("/")[0]))
        if HAS_FIXED:
            for op in ("ppr", "sgc"):
                mu, sd = [], []
                for sh in SHELLS[:3]:
                    v = [r["mae"] for r in R.cell_fixed_ops(g3, task, sh, "h32l4", 1000).get(op, {}).values()]
                    mu.append(np.mean(v) if v else np.nan); sd.append(np.std(v, ddof=1) if len(v) > 1 else 0)
                ax.errorbar([x + {"ppr": -0.22, "sgc": 0.22}[op] for x in X], mu, yerr=sd, color=C[op], marker=MK[op], ls=LS[op], capsize=1.5, lw=0.9, ms=3.2, elinewidth=0.6, label=LBL[op])
        cms = [R.summarise(R.cell(g3, task, sh, ARMS3[0], "h32l4", 1000))[1] for sh in SHELLS[:3]]
        ax.plot(X, cms, color=C["const"], ls=":", lw=0.9, label="constant predictor")
        ax.set_xticks(X); ax.set_xticklabels(["264", "1584", "3168"]); ax.set_xlabel("satellites in shell"); ax.set_title(task + " field", fontsize=8)
    axes[0].set_ylabel("MAE, mean $\\pm$ sd")
    h, l = axes[1].get_legend_handles_labels()
    fig.legend(h, l, loc="lower center", ncol=3, fontsize=6.5, bbox_to_anchor=(0.5, -0.04), handlelength=2.2, columnspacing=1.0)
    fig.subplots_adjust(bottom=0.38, wspace=0.08)
    save(fig, "fig4-scale-1000ep")

    def grid3_tables(key, fname, fname_inf, rows=None, arms=None):
        rows = g3 if rows is None else rows; arms = ARMS3 if arms is None else arms
        T = ["\\begin{tabular}{@{}lrrllllcl@{}}\n\\toprule\ntask, $t$ arm & $N$ & const & GCN & heat & walk & leader & heat:walk & verdict \\\\\n\\midrule"]
        V = {}; cells = []
        for task in ("hops", "delay"):
            for arm in arms:
                T.append("\\multicolumn{9}{@{}l}{\\emph{%s field, %s}} \\\\" % (task, arm_label(arm)))
                for sh in SHELLS[:3]:
                    c = R.cell(rows, task, sh, arm, "h32l4", 1000)
                    st, cm, gain, vd, ld = R.summarise(c, key); ps = R.paired_stats(c, key)
                    V[(task, sh, arm)] = (vd, ld, ps); cells.append((task, sh, arm, ps))
                    T.append("& %d & %.3f & %s & %s & %s & %s & %d:%d & %s \\\\" % (NN[sh], cm, pm(st, "gcn"), pm(st, "heat"), pm(st, "qw"), ld, ps["wins_a"], ps["wins_b"], vd.replace("<", "$<$")))
                T.append("\\addlinespace[2pt]")
        T.append("\\bottomrule\n\\end{tabular}"); tabfile(fname, T)
        # --- bang suy dien: Holm can p cua MOI o truoc, nen tinh xong roi moi in NHOM + SO cung nhau
        pv = [ps["p_wilcoxon"] for (_, _, _, ps) in cells]; ph = R.holm(pv)
        I = ["\\begin{tabular}{@{}lrrcrrr@{}}\n\\toprule\n"
             "& & \\multicolumn{2}{c}{$\\bar d = \\bar e_{\\mathrm{heat}}-\\bar e_{\\mathrm{walk}}$} & \\multicolumn{3}{c}{two-sided $p$} \\\\\n"
             "\\cmidrule(lr){3-4}\\cmidrule(lr){5-7}\n"
             "$t$ arm & $N$ & mean & 95\\% CI & sign & Wilcoxon & Holm \\\\\n\\midrule"]
        k = 0; cur_task = None
        for (task, sh, arm, ps) in cells:
            if task != cur_task:
                I.append("\\multicolumn{7}{@{}l}{\\emph{%s field}} \\\\" % task); cur_task = task
            first = (sh == SHELLS[0])
            star = "$^{*}$" if (ph[k] == ph[k] and ph[k] < 0.05) else ""
            I.append("%s & %d & $%+.4f$ & $[%+.4f,\\,%+.4f]$ & %s & %s & %s%s \\\\"
                     % (arm_label(arm) if first else "", NN[sh], ps["diff"], ps["ci_lo"], ps["ci_hi"], fp(ps["p_sign"]), fp(ps["p_wilcoxon"]), fp(ph[k]), star))
            if sh == SHELLS[2]:
                I.append("\\addlinespace[2pt]")
            k += 1
        I.append("\\bottomrule\n\\end{tabular}"); tabfile(fname_inf, I)
        rob = {}
        for task in ("hops", "delay"):
            for sh in SHELLS[:3]:
                vs = [V[(task, sh, a)][0] for a in arms]
                rob[(task, sh)] = "heat" if all(v == "heat" for v in vs) else "walk" if all(v == "walk" for v in vs) else "no"
        out = dict(rob=rob, nh=sum(v == "heat" for v in rob.values()), nw=sum(v == "walk" for v in rob.values()),
                   lh=sum(1 for v in V.values() if v[1] == "heat"), lw=sum(1 for v in V.values() if v[1] == "walk"),
                   nsig=sum(1 for p in ph if p == p and p < 0.05), nsigraw=sum(1 for p in pv if p == p and p < 0.05),
                   ncells=len(pv), V=V, ph=ph)
        return out

    G = grid3_tables("mae", "tab2-grid3.tex", "tab2b-grid3-inference.tex")
    M("numGthreeCells", 6); M("numGthreeHeatRobust", G["nh"]); M("numGthreeWalkRobust", G["nw"])
    M("numGthreeArmCells", G["ncells"]); M("numGthreeLeadHeat", G["lh"]); M("numGthreeLeadWalk", G["lw"])
    M("numGthreeSigHolm", G["nsig"]); M("numGthreeSigRaw", G["nsigraw"])
    for (task, sh), v in G["rob"].items():
        M("numGthree" + task.capitalize() + SHNAME[sh] + "Robust", v)
    GA = grid3_tables("aurc", "tab5-aurc.tex", "tab5b-aurc-inference.tex")
    M("numAurcHeatRobust", GA["nh"]); M("numAurcWalkRobust", GA["nw"]); M("numAurcSigHolm", GA["nsig"]); M("numAurcSigRaw", GA["nsigraw"])
    M("numAurcHeatWinsArm", sum(1 for v in GA["V"].values() if v[0] == "heat")); M("numAurcWalkWinsArm", sum(1 for v in GA["V"].values() if v[0] == "walk"))
    ps_rob = [G["V"][(t, s, a)][2]["p_sign"] for (t, s), v in G["rob"].items() if v == "heat" for a in ARMS3]
    M("numGthreeRobustMaxPsign", "%.3f" % max(ps_rob) if ps_rob else "---"); M("numGthreeRobustMinPsign", "%.3f" % min(ps_rob) if ps_rob else "---")
    # cac o "walk dan theo trung binh" nhung phan quyet hoa
    M("numGthreeWalkLeadTie", sum(1 for v in G["V"].values() if v[1] == "walk" and v[0] == "tie"))

    T = ["\\begin{tabular}{@{}lrlcccc@{}}\n\\toprule\ntask & $N$ & $t$ arm & MAE heat:walk & far-node heat:walk & moved & verdict MAE / far-node \\\\\n\\midrule"]
    moved = []
    for task in ("hops", "delay"):
        for sh in SHELLS[:3]:
            for arm in ARMS3:
                v, l, p = G["V"][(task, sh, arm)]; vA, lA, pA = GA["V"][(task, sh, arm)]
                mv = abs(p["wins_a"] - pA["wins_a"]); moved.append(mv)
                T.append("%s & %d & %s & %d:%d & %d:%d & %d & %s / %s \\\\" % (task, NN[sh], arm_label(arm), p["wins_a"], p["wins_b"], pA["wins_a"], pA["wins_b"], mv, v.replace("<", "$<$"), vA.replace("<", "$<$")))
    T.append("\\bottomrule\n\\end{tabular}"); tabfile("tab-swap.tex", T)
    M("numSwapMedianMoved", int(np.median(moved))); M("numSwapMaxMoved", int(max(moved)))
    M("numSwapCellsMovedTwoPlus", sum(1 for m in moved if m >= 2)); M("numSwapCells", len(moved))

    T = ["\\begin{tabular}{@{}lcccc@{}}\n\\toprule\nfloor $g$ & majority $\\geq 6/10$ & $\\geq 7/10$ & $\\geq 8/10$ & rankable cells (grid 1, $\\geq$1584, hop) \\\\\n\\midrule"]
    for gth, gname in ((0.01, "One"), (0.02, "Two"), (0.05, "Five"), (0.10, "Ten")):
        cols = []
        for kth in (6, 7, 8):
            robk = robw = 0
            for task in ("hops", "delay"):
                for sh in SHELLS[:3]:
                    vs = [R.summarise(R.cell(g3, task, sh, a, "h32l4", 1000), "mae", gth, kth)[3] for a in ARMS3]
                    robk += all(v == "heat" for v in vs); robw += all(v == "walk" for v in vs)
            cols.append("%d heat / %d walk" % (robk, robw))
            if kth == 7:
                M("numRobustHeatAtG" + gname, robk)
            if kth == 8 and gth == 0.05:
                M("numRobustHeatAtMajEight", robk); M("numRobustWalkAtMajEight", robw)
        nr = sum(1 for cfg in CFGS for a in ARMS for sh in SHELLS[1:] if R.summarise(R.cell(g12, "hops", sh, a, cfg, 200), "mae", gth, 7)[3] != "floor")
        T.append("%.2f & %s & %d of 24 \\\\" % (gth, " & ".join(cols), nr))
        M("numRankableLargeAtG" + gname, nr)
    T.append("\\bottomrule\n\\end{tabular}"); tabfile("tab-sens.tex", T)

    T = ["\\begin{tabular}{@{}lrrrr@{}}\n\\toprule\noperator & excluded & of which had escaped & of which at floor & valid \\\\\n\\midrule"]
    for op in CORE + (("ppr", "sgc") if HAS_FIXED else ()):
        rs = [r for r in g3 if r["op"] == op]; ex = [r for r in rs if r["pathology"]]
        T.append("%s & %d/%d & %d & %d & %d \\\\" % (OPN[op], len(ex), len(rs), sum(r["escaped"] for r in ex), sum(not r["escaped"] for r in ex), len(rs) - len(ex)))
        M("numCollapse" + OPN[op].capitalize(), "%d/%d" % (len(ex), len(rs))); M("numCollapse" + OPN[op].capitalize() + "Escaped", sum(r["escaped"] for r in ex))
        if op == "qw":
            T.append("\\midrule")
    T.append("\\bottomrule\n\\end{tabular}"); tabfile("tab6-collapse.tex", T)
    rises = [max((th[i + 1] - th[i]) / th[i] for i in range(2)) for th in (json.loads(r["loss_thirds"]) for r in g3 if r["op"] in CORE) if any(th[i + 1] > th[i] * 1.01 for i in range(2))]
    M("numGridThreeRiseMaxPct", round(100 * max(rises)))
    for task in ("hops", "delay"):
        gs = [R.summarise(R.cell(g3, task, sh, a, "h32l4", 1000))[2] for a in ARMS3 for sh in SHELLS[:3]]
        M("numGthree" + task.capitalize() + "GainMin", round(100 * min(gs))); M("numGthree" + task.capitalize() + "GainMax", round(100 * max(gs)))
    for sh in SHELLS[:3]:
        gs = []
        for arm in ARMS3:
            st, cm, gain, vd, ld = R.summarise(R.cell(g3, "hops", sh, arm, "h32l4", 1000)); gs.append(100 * (cm - st["gcn"][0]) / cm)
        M("numGthreeGcnGain" + SHNAME[sh], round(max(gs), 1))
    st, cm, gain, vd, ld = R.summarise(R.cell(g3, "hops", "s264", "softplus/t0=0.5", "h32l4", 1000))
    M("numGthreeGcnSdMax", "%.3f" % max(R.summarise(R.cell(g3, t_, s_, a_, "h32l4", 1000))[0]["gcn"][1] for t_ in ("hops", "delay") for s_ in SHELLS[:3] for a_ in ARMS3))
    M("numGthreeHopsSmallHeat", "%.3f" % st["heat"][0]); M("numGthreeHopsSmallHeatSd", "%.3f" % st["heat"][1])
    M("numGthreeHopsSmallWalk", "%.3f" % st["qw"][0]); M("numGthreeHopsSmallWalkSd", "%.3f" % st["qw"][1]); M("numGthreeHopsSmallConst", "%.3f" % cm)
    rr = [st["qw"][1] / st["heat"][1] for st in (R.summarise(R.cell(g3, t, s, a, "h32l4", 1000))[0] for t in ("hops", "delay") for a in ARMS3 for s in SHELLS[:3]) if st["heat"][1] > 0]
    M("numSdRatioGeThree", sum(r >= 3 for r in rr)); M("numSdRatioLtOne", sum(r < 1 for r in rr)); M("numSdRatioCells", len(rr)); M("numSdRatioMedian", "%.2f" % np.median(rr))
    T = ["\\begin{tabular}{@{}lrrrrrrr@{}}\n\\toprule\n& & \\multicolumn{2}{c}{GCN} & \\multicolumn{2}{c}{heat} & \\multicolumn{2}{c}{walk} \\\\\n\\cmidrule{3-4}\\cmidrule{5-6}\\cmidrule{7-8}\ntask & $N$ & train & test & train & test & train & test \\\\\n\\midrule"]
    for task in ("hops", "delay"):
        for sh in SHELLS[:3]:
            c = R.cell(g3, task, sh, "softplus/t0=0.5", "h32l4", 1000); row = []
            for op in CORE:
                v = list(c.get(op, {}).values()); row += ["%.3f" % np.mean([r["train_mae"] for r in v]), "%.3f" % np.mean([r["mae"] for r in v])]
            T.append("%s & %d & %s \\\\" % (task, NN[sh], " & ".join(row)))
    T.append("\\bottomrule\n\\end{tabular}"); tabfile("tab-fit.tex", T)
    gaps = [abs(np.mean([r["train_mae"] for r in c.get(op, {}).values()]) - np.mean([r["mae"] for r in c.get(op, {}).values()]))
            for task in ("hops", "delay") for sh in SHELLS[:3] for c in [R.cell(g3, task, sh, "softplus/t0=0.5", "h32l4", 1000)] for op in CORE]
    M("numFitMaxGap", "%.4f" % max(gaps))
    gaps_h = [abs(np.mean([r["train_mae"] for r in c.get(op, {}).values()]) - np.mean([r["mae"] for r in c.get(op, {}).values()]))
              for sh in SHELLS[:3] for c in [R.cell(g3, "hops", sh, "softplus/t0=0.5", "h32l4", 1000)] for op in CORE]
    M("numFitMaxGapHops", "%.5f" % max(gaps_h))

    if HAS_FIXED:
        T = ["\\begin{tabular}{@{}lrrllcllr@{}}\n\\toprule\n& & & \\multicolumn{2}{c}{200 epochs} & & \\multicolumn{3}{c}{1000 epochs} \\\\\n\\cmidrule{4-5}\\cmidrule{7-9}\ntask & $N$ & const & PPR & SGC & & PPR & SGC & best of heat/walk \\\\\n\\midrule"]
        def s_(c, op, n=True):
            v = [r["mae"] for r in c.get(op, {}).values()]
            if not v:
                return "---"
            return ("%.3f $\\pm$ %.3f" % (np.mean(v), np.std(v, ddof=1) if len(v) > 1 else 0)) + ((" (%d)" % len(v)) if n else "")
        for task in ("hops", "delay"):
            for sh in SHELLS:
                c2 = R.cell_fixed_ops(g12, task, sh, "h32l4", 200); c3 = R.cell_fixed_ops(g3, task, sh, "h32l4", 1000)
                best = "---"
                if sh != "s4400":
                    best = "%.3f" % min(min(R.summarise(R.cell(g3, task, sh, a, "h32l4", 1000))[0][op][0] for op in ("heat", "qw")) for a in ARMS3)
                cm_ = np.mean([r["const_mae"] for op in c2 for r in c2[op].values()]) if c2 else float("nan")
                T.append("%s & %d & %.3f & %s & %s & & %s & %s & %s \\\\" % (task, NN[sh], cm_, s_(c2, "ppr", False), s_(c2, "sgc", False), s_(c3, "ppr"), s_(c3, "sgc"), best))
                for op in ("ppr", "sgc"):
                    if c3.get(op):
                        v = [r["mae"] for r in c3[op].values()]; cc = np.mean([r["const_mae"] for r in c3[op].values()])
                        M("numFixedGain" + OPN[op].capitalize() + task.capitalize() + SHNAME[sh], round(100 * (cc - np.mean(v)) / cc, 1))
                        M("numFixed" + OPN[op].capitalize() + task.capitalize() + SHNAME[sh] + "Sd", "%.3f" % (np.std(v, ddof=1) if len(v) > 1 else 0))
                        M("numFixed" + OPN[op].capitalize() + task.capitalize() + SHNAME[sh] + "N", len(v))
        T.append("\\bottomrule\n\\end{tabular}"); tabfile("tab-fixed.tex", T)
        # macro: kernel pho tot nhat vs baseline co dinh tot nhat, 1000 epoch, tung shell (hops)
        for task in ("hops", "delay"):
            for sh in SHELLS[:3]:
                c3 = R.cell_fixed_ops(g3, task, sh, "h32l4", 1000)
                fixed_best = min(np.mean([r["mae"] for r in c3[op].values()]) for op in ("ppr", "sgc") if c3.get(op))
                spec_best = min(min(R.summarise(R.cell(g3, task, sh, a, "h32l4", 1000))[0][op][0] for op in ("heat", "qw")) for a in ARMS3)
                M("numFixedBest" + task.capitalize() + SHNAME[sh], "%.3f" % fixed_best)
                M("numSpecBest" + task.capitalize() + SHNAME[sh], "%.3f" % spec_best)
                fb3, sb3 = float("%.3f" % fixed_best), float("%.3f" % spec_best)     # tu gia tri in trong bang
                M("numFixedGapPct" + task.capitalize() + SHNAME[sh], round(100 * (fb3 - sb3) / fb3, 1))
                # review vong 2 (3e): MOT dinh nghia cho ca hai bien: trong moi nhanh lay kernel THAP HON
                # (dung cot cua bang), roi nhanh tot nhat / te nhat cua dai luong do
                lower = [min(R.summarise(R.cell(g3, task, sh, a, "h32l4", 1000))[0][op][0] for op in ("heat", "qw")) for a in ARMS3]
                spec_worst = max(lower)
                assert abs(min(lower) - spec_best) < 1e-12
                M("numSpecWorst" + task.capitalize() + SHNAME[sh], "%.3f" % spec_worst)
                M("numFixedGapWorstPct" + task.capitalize() + SHNAME[sh], round(100 * (fb3 - float("%.3f" % spec_worst)) / fb3, 1))
        both = sum(1 for task in ("hops", "delay") for sh in SHELLS[:3]
                   if all(max(R.summarise(R.cell(g3, task, sh, a, "h32l4", 1000))[0][op][0] for a in ARMS3) <
                          min(np.mean([r["mae"] for r in R.cell_fixed_ops(g3, task, sh, "h32l4", 1000)[o].values()]) for o in ("ppr", "sgc"))
                          for op in ("heat", "qw")))
        M("numBothBeatFixedCells", both)
        c3 = R.cell_fixed_ops(g3, "hops", "s1584", "h32l4", 1000)
        for op in ("ppr", "sgc"):
            rs = list(c3[op].values())
            M("numFixed" + OPN[op].capitalize() + "HopsShellOneAtConst", sum(1 for r in rs if r["mae"] > 0.98 * r["const_mae"]))
            M("numFixed" + OPN[op].capitalize() + "HopsShellOneEscaped", sum(1 for r in rs if r["mae"] < 0.9 * r["const_mae"]))
        # baseline co dinh o 200 epoch: co roi san o >=1584 khong
        fx = [r for r in g12 if r["op"] in ("ppr", "sgc") and r["shell"] != "s264" and not r["pathology"]]
        M("numFixedLargeMaxGainPct", round(100 * max((r["const_mae"] - r["mae"]) / r["const_mae"] for r in fx), 1))


# ================================================================ REVIEW VONG 2: luc cua luat 6, huong cua CI, phep thu gop, reach do duoc
if g3:
    # --- (2a) dac tinh van hanh cua luat 6: p toi thieu theo |S|, so o khong the bac
    cells_ps = {}
    for key in ("mae", "aurc"):
        for task in ("hops", "delay"):
            for arm in ARMS3:
                for sh in SHELLS[:3]:
                    cells_ps[(key, task, sh, arm)] = R.paired_stats(R.cell(g3, task, sh, arm, "h32l4", 1000), key)
    m_cells = len(ARMS3) * 6
    thr = 0.05 / m_cells
    T = ["\\begin{tabular}{@{}rrrrlr@{}}\n\\toprule\n$|S|$ & min.\\ $p$ & $\\times %d$ & rejectable after Holm & cells & MDE ($\\alpha{=}0.05$, 80\\%% power) \\\\\n\\midrule" % m_cells]
    ns = sorted({ps["n"] for (k, _, _, _), ps in cells_ps.items() if k == "mae"})
    n_cannot = n_sweep = 0
    for n in ns:
        mp = R.wilcoxon_min_p(n); can = mp < thr
        cnt = sum(1 for (k, _, _, _), ps in cells_ps.items() if k == "mae" and ps["n"] == n)
        # hieu ung nho nhat phat hien duoc (MDE) o alpha 0.05 chua hieu chinh, sd cua tung o (tu CI bootstrap), trung vi
        pw = []
        for (k, _, _, _), ps in cells_ps.items():
            if k == "mae" and ps["n"] == n:
                sd = (ps["ci_hi"] - ps["ci_lo"]) / (2 * 1.96) * np.sqrt(n)
                pw.append(R.mde_wilcoxon(sd, n, 0.05))
        mde = np.nanmedian(pw) if pw and not all(x != x for x in pw) else float("nan")
        T.append("%d & %.5f & %.3f & %s & %d & %s \\\\" % (n, mp, min(1.0, m_cells * mp), "yes, only on $%d{:}0$" % n if can else "no", cnt, ("%.3f" % mde) if mde == mde else "---"))
        if not can:
            n_cannot += cnt
        else:
            n_sweep += cnt
    T.append("\\bottomrule\n\\end{tabular}"); tabfile("tab-power.tex", T)
    M("numPowerCannotReject", n_cannot); M("numPowerNeedSweep", n_sweep); M("numHolmThreshold", "%.5f" % thr)
    M("numPowerMinPTen", "%.5f" % R.wilcoxon_min_p(10)); M("numPowerMinPNine", "%.5f" % R.wilcoxon_min_p(9))
    # luc cua o hieu ung lon nhat (hops/relu 0.5/264) tai alpha 0.05 va tai nguong Holm khat nhat
    ps0 = cells_ps[("mae", "hops", "s264", "relu/t0=0.5")]
    sd0 = (ps0["ci_hi"] - ps0["ci_lo"]) / (2 * 1.96) * np.sqrt(ps0["n"])
    pw0 = R.power_wilcoxon(ps0["diff"], sd0, ps0["n"], (0.05, thr))
    M("numPowerLargestRaw", "%.2f" % pw0[0.05]); M("numPowerLargestHolm", "%.2f" % pw0[thr]); M("numPowerLargestN", ps0["n"]); M("numPowerLargestD", "%.4f" % ps0["diff"])
    pw10 = R.power_wilcoxon(ps0["diff"], sd0, 10, (0.05, thr)); M("numPowerLargestHolmIfTen", "%.2f" % pw10[thr])
    # --- (2b) huong cua CI va cua p tho
    for key, nm in (("mae", ""), ("aurc", "Aurc")):
        ex = [ps for (k, _, _, _), ps in cells_ps.items() if k == key and (ps["ci_lo"] > 0 or ps["ci_hi"] < 0)]
        M("numCIExclZero" + nm, len(ex)); M("numCIExclZeroHeat" + nm, sum(ps["diff"] < 0 for ps in ex)); M("numCIExclZeroWalk" + nm, sum(ps["diff"] > 0 for ps in ex))
        sig = [ps for (k, _, _, _), ps in cells_ps.items() if k == key and ps["p_wilcoxon"] < 0.05]
        M("numRawSigHeat" + nm, sum(ps["diff"] < 0 for ps in sig)); M("numRawSigWalk" + nm, sum(ps["diff"] > 0 for ps in sig))
        ex264 = sum(1 for (k, t, sh, a), ps in cells_ps.items() if k == key and sh == "s264" and (ps["ci_lo"] > 0 or ps["ci_hi"] < 0))
        M("numCIExclZeroSmall" + nm, ex264)
    M("numCIExpectedNull", "%.1f" % (0.05 * m_cells))
    # --- (2f) phep thu GOP: mot phep thu moi (task, shell), Holm tren 6
    for key, fname, nm in (("mae", "tab-pooled.tex", ""), ("aurc", "tab-pooled-aurc.tex", "Aurc")):
        P = []; keys = []
        for task in ("hops", "delay"):
            for sh in SHELLS[:3]:
                P.append(R.pooled_stats(g3, task, sh, ARMS3, "h32l4", 1000, key)); keys.append((task, sh))
        ph6 = R.holm([q["p_wilcoxon"] for q in P])
        T = ["\\begin{tabular}{@{}lrrrrrrrrr@{}}\n\\toprule\n& & & \\multicolumn{2}{c}{$\\bar d$ over arms} & \\multicolumn{3}{c}{two-sided $p$} & & \\\\\n\\cmidrule(lr){4-5}\\cmidrule(lr){6-8}\ntask & $N$ & seeds & mean & 95\\% CI & sign & Wilcoxon & Holm (6) & heat:walk & MDE \\\\\n\\midrule"]
        nsig6 = 0; pws = []
        for (task, sh), q, h6 in zip(keys, P, ph6):
            star = "$^{*}$" if h6 < 0.05 else ""
            nsig6 += h6 < 0.05
            pw = R.mde_wilcoxon(q["sd"], q["n"], 0.05 / 6); pws.append(pw)
            T.append("%s & %d & %d & $%+.4f$ & $[%+.4f,\\,%+.4f]$ & %s & %s & %s%s & %d:%d & %s \\\\" % (task, NN[sh], q["n"], q["diff"], q["ci_lo"], q["ci_hi"], fp(q["p_sign"]), fp(q["p_wilcoxon"]), fp(h6), star, q["wins_a"], q["wins_b"], fm(pw)))
            M("numPooled" + nm + task.capitalize() + SHNAME[sh] + "Mde", fm(pw))
            M("numPooled" + nm + task.capitalize() + SHNAME[sh] + "Holm", fp(h6)); M("numPooled" + nm + task.capitalize() + SHNAME[sh] + "Wins", "%d:%d" % (q["wins_a"], q["wins_b"]))
            M("numPooled" + nm + task.capitalize() + SHNAME[sh] + "D", "%+.4f" % q["diff"])
        T.append("\\bottomrule\n\\end{tabular}"); tabfile(fname, T)
        M("numPooledSigHolm" + nm, nsig6); M("numPooledMdeMin" + nm, fm(np.nanmin(pws))); M("numPooledMdeMax" + nm, fm(np.nanmax(pws)))
        M("numPooledMdeSmall" + nm, fm(np.nanmax([pws[0], pws[3]]))); M("numPooledMdeLargeMin" + nm, fm(np.nanmin([pws[1], pws[2], pws[4], pws[5]])))
        M("numPooledMinPHolmSix", "%.5f" % R.wilcoxon_min_p(10)); M("numPooledMinHolmSix", "%.3f" % (6 * R.wilcoxon_min_p(10)))
        M("numPooledHeatLead" + nm, sum(q["diff"] < 0 for q in P)); M("numPooledWalkLead" + nm, sum(q["diff"] > 0 for q in P))
        M("numPooledMinSeeds" + nm, min(q["n"] for q in P)); M("numPooledThreshold" + nm, "%.4f" % (0.05 / 6))
        M("numPooledCIExcl" + nm, sum(1 for q in P if q["ci_lo"] > 0 or q["ci_hi"] < 0))
    pd_ = abs(float(NUM["numPrelimWalkMAE"]) - float(NUM["numPrelimHeatMAE"]))
    M("numPrelimDiff", "%.3f" % pd_); M("numMdeRatioHopsShellOne", "%.1f" % (float(NUM["numPooledHopsShellOneMde"]) / pd_))
    # --- (3b, 3c) san far-node voi hang so far-node dung
    fl = [(task, sh, arm) for (k, task, sh, arm) in cells_ps if k == "aurc" and R.summarise(R.cell(g3, task, sh, arm, "h32l4", 1000), "aurc")[3] == "floor"]
    M("numAurcFloorCells", len(fl)); M("numAurcFloorCellsLarge", sum(1 for (_, sh, _) in fl if sh != "s264")); M("numAurcFloorCellsSmall", sum(1 for (_, sh, _) in fl if sh == "s264"))
    ga = [R.summarise(R.cell(g3, task, sh, arm, "h32l4", 1000), "aurc")[2] for (k, task, sh, arm) in cells_ps if k == "aurc" and sh != "s264"]
    M("numAurcGainLargeMin", round(100 * min(ga), 1)); M("numAurcGainLargeMax", round(100 * max(ga), 1))
    M("numConstAurcHopsShellOne", "%.3f" % R.summarise(R.cell(g3, "hops", "s1584", ARMS3[0], "h32l4", 1000), "aurc")[1])
    M("numConstMaeHopsShellOne", "%.3f" % R.summarise(R.cell(g3, "hops", "s1584", ARMS3[0], "h32l4", 1000), "mae")[1])
    M("numConstAurcHopsSmall", "%.3f" % R.summarise(R.cell(g3, "hops", "s264", ARMS3[0], "h32l4", 1000), "aurc")[1])
    # --- (2c) reach do duoc, tu analysis/fields.py
    RE = json.load(open(os.path.join(RES, "reach.json")))
    T = ["\\begin{tabular}{@{}lrrr@{}}\n\\toprule\noperator & 264 & 1584 & 3168 \\\\\n\\midrule"]
    T.append("eccentricity of the destination & %s \\\\" % " & ".join("%.0f" % RE[sh]["ecc"] for sh in SHELLS[:3]))
    T.append("\\addlinespace[2pt]\\multicolumn{4}{@{}l}{\\emph{per layer, at the learned $t$ of Table~\\ref{tab:tlearned}}} \\\\")
    T.append("GCN step & %s \\\\" % " & ".join("%.1f" % RE[sh]["gcn"] for sh in SHELLS[:3]))
    for op in ("heat", "qw"):
        T.append("%s, layers 1--4 & %s \\\\" % (OPN[op], " & ".join("/".join("%.1f" % v for v in RE[sh][op]["per_layer"]) for sh in SHELLS[:3])))
    T.append("PPR, $\\alpha{=}0.05$, 20 steps (round 1) & %s \\\\" % " & ".join("%.1f" % RE[sh]["ppr_trunc_a0.05_K20"]["per_layer"] for sh in SHELLS[:3]))
    for a in (0.2, 0.05, 0.02, 0.01):
        T.append("PPR exact, $\\alpha{=}%g$ & %s \\\\" % (a, " & ".join("%.1f" % RE[sh]["ppr_exact_a%g" % a]["per_layer"] for sh in SHELLS[:3])))
    for K in (1, 2, 8, 32, 64):
        T.append("SGC, $K'{=}%d$ & %s \\\\" % (K, " & ".join("%.1f" % RE[sh]["sgc_K%d" % K]["per_layer"] for sh in SHELLS[:3])))
    T.append("\\addlinespace[2pt]\\multicolumn{4}{@{}l}{\\emph{composed over four layers}} \\\\")
    T.append("GCN & %s \\\\" % " & ".join("%.1f" % RE[sh]["gcn_composed"] for sh in SHELLS[:3]))
    for op in ("heat", "qw"):
        T.append("%s & %s \\\\" % (OPN[op], " & ".join("%.1f" % RE[sh][op]["composed"] for sh in SHELLS[:3])))
    T.append("PPR, $\\alpha{=}0.05$, 20 steps & %s \\\\" % " & ".join("%.1f" % RE[sh]["ppr_trunc_a0.05_K20"]["composed"] for sh in SHELLS[:3]))
    T.append("SGC, $K'{=}8$ & %s \\\\" % " & ".join("%.1f" % RE[sh]["sgc_K8"]["composed"] for sh in SHELLS[:3]))
    T.append("SGC, $K'{=}64$ & %s \\\\" % " & ".join("%.1f" % RE[sh]["sgc_K64"]["composed"] for sh in SHELLS[:3]))
    T.append("\\bottomrule\n\\end{tabular}"); tabfile("tab-reach.tex", T)
    for sh in SHELLS[:3]:
        M("numReachHeatMean" + SHNAME[sh], "%.1f" % np.mean(RE[sh]["heat"]["per_layer"])); M("numReachWalkMean" + SHNAME[sh], "%.1f" % np.mean(RE[sh]["qw"]["per_layer"]))
        M("numReachHeatComposed" + SHNAME[sh], "%.1f" % RE[sh]["heat"]["composed"]); M("numReachWalkComposed" + SHNAME[sh], "%.1f" % RE[sh]["qw"]["composed"])
        M("numReachPprRoundOne" + SHNAME[sh], "%.1f" % RE[sh]["ppr_trunc_a0.05_K20"]["per_layer"]); M("numReachSgcEight" + SHNAME[sh], "%.1f" % RE[sh]["sgc_K8"]["per_layer"])
        M("numReachSgcSixtyFour" + SHNAME[sh], "%.1f" % RE[sh]["sgc_K64"]["per_layer"]); M("numReachPprExactOne" + SHNAME[sh], "%.1f" % RE[sh]["ppr_exact_a0.01"]["per_layer"])
        M("numReachHeatLayerOne" + SHNAME[sh], "%.1f" % RE[sh]["heat"]["per_layer"][0]); M("numReachWalkLayerFour" + SHNAME[sh], "%.1f" % RE[sh]["qw"]["per_layer"][3])
    M("numReachRatioShellOne", "%.1f" % (np.mean(RE["s1584"]["heat"]["per_layer"]) / RE["s1584"]["sgc_K8"]["per_layer"]))

    # --- (2c) thang baseline, (seam) nhanh cat seam, (2e) float64: chi khi VPS da tra ket qua
    rev2 = os.path.join(RES, "rev2")
    lad = R.load([os.path.join(rev2, "sweep_*.csv")]) if os.path.isdir(rev2) else []
    HAS_LADDER = len(lad) > 0
    if HAS_LADDER:
        def lad_cell(task, sh, op, key_, val):
            return [r for r in lad if (r["task"], r["shell"], r["op"]) == (task, sh, op) and not r["pathology"] and abs(r[key_] - val) < 1e-9]
        cfgs_l = [("sgc", "sgc_k", K, "SGC $K'{=}%d$" % K) for K in (2, 8, 32, 64)] + [("ppr", "ppr_alpha", a, "PPR exact $\\alpha{=}%g$" % a) for a in (0.2, 0.05, 0.02, 0.01)]
        cols = [(task, sh) for task in ("hops", "delay") for sh in SHELLS[:3]]
        best = {}; cm_ = {}
        for (task, sh) in cols:
            means = []
            for op, kf, val, _ in cfgs_l:
                v = [r["mae"] for r in lad_cell(task, sh, op, kf, val)]
                if v: means.append((np.mean(v), op, val, len(v)))
            c3 = R.cell_fixed_ops(g3, task, sh, "h32l4", 1000)
            for op in ("ppr", "sgc"):          # baseline vong 1 cung vao cuoc dua
                v = [r["mae"] for r in c3.get(op, {}).values()]
                if v: means.append((np.mean(v), op + "_r1", None, len(v)))
            best[(task, sh)] = min(means) if means else (float("nan"), "", None, 0)
            cm_[(task, sh)] = np.mean([r["const_mae"] for r in lad if (r["task"], r["shell"]) == (task, sh)])
        def sdn(v):
            return ("%.3f $\\pm$ %.3f (%d)" % (np.mean(v), np.std(v, ddof=1) if len(v) > 1 else 0, len(v))) if v else "---"
        excl = []
        # review vong 3 (3e): sd + n cho moi rung; bang xep theo KHOI tac vu de vua khung
        T = ["\\begin{tabular}{@{}lrrr@{}}\n\\toprule\noperator & 264 & 1584 & 3168 \\\\\n\\midrule"]
        for task in ("hops", "delay"):
            T.append("\\multicolumn{4}{@{}l}{\\emph{%s field}} \\\\" % task)
            T.append("constant predictor & %s \\\\" % " & ".join("%.3f" % cm_[(task, sh)] for sh in SHELLS[:3]))
            for op, kf, val, lab in cfgs_l:
                row = []
                for sh in SHELLS[:3]:
                    v = [r["mae"] for r in lad_cell(task, sh, op, kf, val)]
                    excl.append(10 - len(v)); row.append(sdn(v))
                T.append("%s & %s \\\\" % (lab, " & ".join(row)))
            for op, lab in (("ppr", "PPR, round 1 ($\\alpha{=}0.05$, 20 steps)"), ("sgc", "SGC, round 1 ($K'{=}8$)")):
                row = []
                for sh in SHELLS[:3]:
                    v = [r["mae"] for r in R.cell_fixed_ops(g3, task, sh, "h32l4", 1000).get(op, {}).values()]
                    excl.append(10 - len(v)); row.append(sdn(v))
                T.append("%s & %s \\\\" % (lab, " & ".join(row)))
            T.append("best rung & %s \\\\" % " & ".join("%.3f" % best[(task, sh)][0] for sh in SHELLS[:3]))
            T.append("spectral, worst $t$ arm & %s \\\\" % " & ".join(NUM["numSpecWorst" + task.capitalize() + SHNAME[sh]] for sh in SHELLS[:3]))
            T.append("spectral, best $t$ arm & %s \\\\" % " & ".join(NUM["numSpecBest" + task.capitalize() + SHNAME[sh]] for sh in SHELLS[:3]))
            if task == "hops":
                T.append("\\addlinespace[3pt]")
        M("numLadderExclMinPct", round(100 * min(excl) / 10)); M("numLadderExclMaxPct", round(100 * max(excl) / 10))
        M("numLadderBestHopsShellOneN", len([r for r in lad_cell("hops", "s1584", "ppr", "ppr_alpha", 0.01)]))
        for (task, sh) in cols:
            bestf = best[(task, sh)]
            M("numLadderBest" + task.capitalize() + SHNAME[sh], "%.3f" % bestf[0])
            lab = {"sgc": "SGC $K'{=}%s$", "ppr": "exact PPR $\\alpha{=}%s$", "ppr_r1": "PPR (round 1)", "sgc_r1": "SGC (round 1)"}[bestf[1]]
            M("numLadderBestName" + task.capitalize() + SHNAME[sh], lab % ("%g" % bestf[2]) if "%s" in lab else lab)
            # review vong 3 (3f): bien tinh tu gia tri DA LAM TRON 3 chu so nhu in trong bang, de doc gia tai tinh duoc
            sb = float(NUM["numSpecBest" + task.capitalize() + SHNAME[sh]]); sw = float(NUM["numSpecWorst" + task.capitalize() + SHNAME[sh]])
            bf3 = float("%.3f" % bestf[0])
            M("numLadderGapBestPct" + task.capitalize() + SHNAME[sh], round(100 * (bf3 - sb) / bf3, 1))
            M("numLadderGapWorstPct" + task.capitalize() + SHNAME[sh], round(100 * (bf3 - sw) / bf3, 1))
        T.append("\\bottomrule\n\\end{tabular}"); tabfile("tab-ladder.tex", T)
        M("numLadderRuns", len(lad)); M("numLadderPathology", sum(r["pathology"] for r in lad))
        # so o (task, shell) ma ca hai kernel, o MOI nhanh, thang baseline TOT NHAT cua thang
        both_l = 0
        for task in ("hops", "delay"):
            for sh in SHELLS[:3]:
                bf = float(NUM["numLadderBest" + task.capitalize() + SHNAME[sh]])
                both_l += all(max(R.summarise(R.cell(g3, task, sh, a, "h32l4", 1000))[0][op][0] for a in ARMS3) < bf for op in ("heat", "qw"))
        M("numBothBeatLadderCells", both_l)
        gb = [float(NUM["numLadderGapBestPct" + t.capitalize() + SHNAME[sh]]) for t in ("hops", "delay") for sh in SHELLS[:3]]
        gw = [float(NUM["numLadderGapWorstPct" + t.capitalize() + SHNAME[sh]]) for t in ("hops", "delay") for sh in SHELLS[:3]]
        M("numLadderGapBestMin", min(gb)); M("numLadderGapBestMax", max(gb)); M("numLadderWorstBehindCells", sum(1 for g in gw if g < 0))
        M("numSpecBestBeatsLadderCells", sum(1 for task in ("hops", "delay") for sh in SHELLS[:3] if float(NUM["numSpecBest" + task.capitalize() + SHNAME[sh]]) < float(NUM["numLadderBest" + task.capitalize() + SHNAME[sh]])))
    M("numHasLadder", int(HAS_LADDER))

    sc = R.load([os.path.join(rev2, "seamcut_*.csv")]) if os.path.isdir(rev2) else []
    HAS_SEAM = any(r["op"] == "qw" for r in sc)
    if HAS_SEAM:
        T = ["\\begin{tabular}{@{}lrlrllllcrr@{}}\n\\toprule\ntask & $N$ & graph & const & GCN & heat & walk & PPR/SGC & heat:walk & $p_{\\mathrm{W}}$ & leader \\\\\n\\midrule"]
        agree = 0; ncmp = 0; nvalid_sc = 0
        for task in ("hops", "delay"):
            for sh in SHELLS[:3]:
                for lab, rows_ in (("torus", g3), ("seam cut", sc)):
                    c = R.cell(rows_, task, sh, "softplus/t0=0.5", "h32l4", 1000)
                    if not c.get("heat"):
                        continue
                    st, cm, gain, vd, ld = R.summarise(c); ps = R.paired_stats(c)
                    cf = R.cell_fixed_ops(rows_, task, sh, "h32l4", 1000)
                    fx = "/".join(("%.3f" % np.mean([r["mae"] for r in cf[op].values()])) if cf.get(op) else "---" for op in ("ppr", "sgc"))
                    T.append("%s & %d & %s & %.3f & %s & %s & %s & %s & %d:%d & %s & %s \\\\" % (task if lab == "torus" else "", NN[sh], lab, cm, pm(st, "gcn"), pm(st, "heat"), pm(st, "qw"), fx, ps["wins_a"], ps["wins_b"], fp(ps["p_wilcoxon"]), ld))
                    if lab == "torus":
                        ld_t = ld
                    else:
                        ncmp += 1; agree += (ld == ld_t)
                        M("numSeam" + task.capitalize() + SHNAME[sh] + "Leader", ld); M("numSeam" + task.capitalize() + SHNAME[sh] + "PW", fp(ps["p_wilcoxon"]))
                        M("numSeam" + task.capitalize() + SHNAME[sh] + "Gain", round(100 * gain, 1))
                T.append("\\addlinespace[2pt]")
        T.append("\\bottomrule\n\\end{tabular}"); tabfile("tab-seam.tex", T)
        M("numSeamCells", ncmp); M("numSeamLeaderAgree", agree); M("numSeamRuns", len(sc)); M("numSeamPathology", sum(r["pathology"] for r in sc if r["op"] in CORE))
        ARMS_SC = sorted({r["arm"] for r in sc if r["op"] in ("heat", "qw")}, key=lambda a: ARMS.index(a) if a in ARMS else 9)
        M("numSeamHopsShellOneArmVerdicts", " / ".join(R.summarise(R.cell(sc, "hops", "s1584", a, "h32l4", 1000))[3].replace("<", "$<$") for a in ARMS_SC))
        M("numSeamArms", len(ARMS_SC)); M("numSeamCoreRuns", sum(1 for r in sc if r["op"] in CORE)); M("numSeamFixedRuns", sum(1 for r in sc if r["op"] in ("ppr", "sgc")))
        M("numSeamPathologyPct", round(100.0 * NUM["numSeamPathology"] / max(NUM["numSeamCoreRuns"], 1), 1))
        GS = grid3_tables("mae", "tab-seam-grid.tex", "tab-seam-grid-inference.tex", sc, ARMS_SC)
        M("numSeamHeatRobust", GS["nh"]); M("numSeamWalkRobust", GS["nw"]); M("numSeamLeadHeat", GS["lh"]); M("numSeamLeadWalk", GS["lw"]); M("numSeamArmCells", GS["ncells"])
        for (task, sh), v in GS["rob"].items():
            M("numSeam" + task.capitalize() + SHNAME[sh] + "Robust", v)
        for key, fname, nm in (("mae", "tab-seam-pooled.tex", ""), ("aurc", "tab-seam-pooled-aurc.tex", "Aurc")):
            P = []; keys = []
            for task in ("hops", "delay"):
                for sh in SHELLS[:3]:
                    P.append(R.pooled_stats(sc, task, sh, ARMS_SC, "h32l4", 1000, key)); keys.append((task, sh))
            ph6 = R.holm([q["p_wilcoxon"] for q in P])
            T = ["\\begin{tabular}{@{}lrrrrrrrrr@{}}\n\\toprule\n& & & \\multicolumn{2}{c}{$\\bar d$ over arms} & \\multicolumn{3}{c}{two-sided $p$} & & \\\\\n\\cmidrule(lr){4-5}\\cmidrule(lr){6-8}\ntask & $N$ & seeds & mean & 95\\% CI & sign & Wilcoxon & Holm (6) & heat:walk & MDE \\\\\n\\midrule"]
            nsig6 = 0
            for (task, sh), q, h6 in zip(keys, P, ph6):
                star = "$^{*}$" if h6 < 0.05 else ""; nsig6 += h6 < 0.05
                pw = R.mde_wilcoxon(q["sd"], q["n"], 0.05 / 6)
                T.append("%s & %d & %d & $%+.4f$ & $[%+.4f,\\,%+.4f]$ & %s & %s & %s%s & %d:%d & %s \\\\" % (task, NN[sh], q["n"], q["diff"], q["ci_lo"], q["ci_hi"], fp(q["p_sign"]), fp(q["p_wilcoxon"]), fp(h6), star, q["wins_a"], q["wins_b"], fm(pw)))
                M("numSeamPooled" + nm + task.capitalize() + SHNAME[sh] + "Holm", fp(h6)); M("numSeamPooled" + nm + task.capitalize() + SHNAME[sh] + "Wins", "%d:%d" % (q["wins_a"], q["wins_b"]))
                M("numSeamPooled" + nm + task.capitalize() + SHNAME[sh] + "D", "%+.4f" % q["diff"]); M("numSeamPooled" + nm + task.capitalize() + SHNAME[sh] + "Mde", fm(pw))
                M("numSeamPooled" + nm + task.capitalize() + SHNAME[sh] + "Leader", "heat" if q["diff"] < 0 else "walk")
            T.append("\\bottomrule\n\\end{tabular}"); tabfile(fname, T)
            M("numSeamPooledSigHolm" + nm, nsig6); M("numSeamPooledHeatSig" + nm, sum(1 for q, h in zip(P, ph6) if h < 0.05 and q["diff"] < 0)); M("numSeamPooledWalkSig" + nm, sum(1 for q, h in zip(P, ph6) if h < 0.05 and q["diff"] > 0))
        # so sanh nguoi dan gop torus vs seam-cut tren 6 o
        agree_p = 0
        for task in ("hops", "delay"):
            for sh in SHELLS[:3]:
                agree_p += NUM["numSeamPooled" + task.capitalize() + SHNAME[sh] + "Leader"] == ("heat" if float(NUM["numPooled" + task.capitalize() + SHNAME[sh] + "D"]) < 0 else "walk")
        M("numSeamPooledLeaderAgree", agree_p)
        c = R.cell(sc, "hops", "s1584", "softplus/t0=0.5", "h32l4", 1000); st_, cm_, _, _, _ = R.summarise(c); ps_ = R.paired_stats(c)
        M("numSeamHopsShellOneWalk", "%.3f" % st_["qw"][0]); M("numSeamHopsShellOneHeat", "%.3f" % st_["heat"][0]); M("numSeamHopsShellOneWins", "%d:%d" % (ps_["wins_a"], ps_["wins_b"]))
        M("numSeamGcnSdMax", "%.3f" % max(R.summarise(R.cell(sc, t_, s_, "softplus/t0=0.5", "h32l4", 1000))[0]["gcn"][1] for t_ in ("hops", "delay") for s_ in SHELLS[:3]))
        # t hoc duoc tren do thi cat seam (nhanh softplus 0.5)
        for sh in SHELLS[:3]:
            for op in ("heat", "qw"):
                c = R.cell(sc, "hops", sh, "softplus/t0=0.5", "h32l4", 1000); ts = np.array([r["t_learned"] for r in c.get(op, {}).values()])
                M("numSeamTlayerOne" + SHNAME[sh] + ("Heat" if op == "heat" else "Walk"), "%.1f" % ts.mean(0)[0] if len(ts) else "---")
        # train vs test tren do thi cat seam (het dang cau)
        gp = [abs(np.mean([r["train_mae"] for r in c.get(op, {}).values()]) - np.mean([r["mae"] for r in c.get(op, {}).values()]))
              for task in ("hops", "delay") for sh in SHELLS[:3] for c in [R.cell(sc, task, sh, "softplus/t0=0.5", "h32l4", 1000)] for op in CORE if c.get(op)]
        M("numSeamFitMaxGap", "%.3f" % max(gp))
        degs = json.load(open(os.path.join(RES, "reach.json")))  # placeholder de giu mot nguon; bac 3 tinh trong fields.py neu can
    if HAS_SEAM:
        # --- review vong 3 (3d): seed thieu o cat-seam hop/1584 va do nhay khi khoi phuc no
        per_seed = {}
        for arm in ARMS_SC:
            c = R.cell(sc, "hops", "s1584", arm, "h32l4", 1000)
            for s_ in sorted(set(c.get("heat", {})) & set(c.get("qw", {}))):
                per_seed.setdefault(s_, []).append(c["heat"][s_]["mae"] - c["qw"][s_]["mae"])
        missing = [s_ for s_ in range(10) if s_ not in per_seed]
        M("numSeamMissingSeeds", ", ".join(str(m) for m in missing) if missing else "none")
        if len(missing) == 1:
            ms = missing[0]
            rows_ms = [r for r in sc if (r["task"], r["shell"], r["seed"]) == ("hops", "s1584", ms) and r["op"] in ("heat", "qw")]
            M("numSeamMissingSeedPathHeat", sum(1 for r in rows_ms if r["op"] == "heat" and r["pathology"])); M("numSeamMissingSeedPathWalk", sum(1 for r in rows_ms if r["op"] == "qw" and r["pathology"]))
            d9 = np.array([np.mean(v) for _, v in sorted(per_seed.items())])
            others = [R.pooled_stats(sc, t_, s2, ARMS_SC, "h32l4", 1000)["p_wilcoxon"] for t_ in ("hops", "delay") for s2 in SHELLS[:3] if (t_, s2) != ("hops", "s1584")]
            scen = {"WalkLarge": max(np.abs(d9)) * 1.01, "WalkSmall": min(np.abs(d9)) * 0.99, "HeatSmall": -min(np.abs(d9)) * 0.99, "HeatLarge": -max(np.abs(d9)) * 1.01}
            for nm_, d10 in scen.items():
                d = np.append(d9, d10); pw_ = R.wilcoxon(d)
                ph_ = R.holm(others[:1] + [pw_] + others[1:])[1]
                M("numSeamRestore" + nm_ + "Raw", fp(pw_)); M("numSeamRestore" + nm_ + "Holm", fp(ph_))
                M("numSeamRestore" + nm_ + "Wins", "%d:%d" % (int((d < 0).sum()), int((d > 0).sum())))
    M("numHasSeam", int(HAS_SEAM))

    # ================================================================ REVIEW VONG 3: float64 cho ba o da chung nhan, doi chung cat ngau nhien, luoi 1 cat seam
    rev3 = os.path.join(RES, "rev3")
    p64 = R.load([os.path.join(rev3, "precision_f64_*.csv")]) if os.path.isdir(rev3) else []
    HAS_P64 = any(r["op"] == "qw" and r["shell"] == "s264" for r in p64)
    if HAS_P64:
        T = ["\\begin{tabular}{@{}llrrrrrrr@{}}\n\\toprule\ncell & precision & seeds & $\\bar d$ & 95\\% CI & heat:walk & Wilcoxon $p$ & Holm (6) & $|S|$ per arm \\\\\n\\midrule"]
        cells64 = [("hops", "s264", g3, "torus", ""), ("delay", "s264", g3, "torus", ""), ("hops", "s1584", sc, "seam cut", "Seam")]
        for task, sh, rows32, glab, tag in cells64:
            arms_ = ARMS3 if rows32 is g3 else ARMS_SC
            q32 = R.pooled_stats(rows32, task, sh, arms_, "h32l4", 1000)
            have64 = [r for r in p64 if (r["task"], r["shell"]) == (task, sh) and r["seam"] == ("keep" if glab == "torus" else "cut")]
            if not any(r["op"] == "qw" for r in have64):
                continue
            arms64 = sorted({r["arm"] for r in have64}, key=lambda a: ARMS.index(a))
            q64 = R.pooled_stats(have64, task, sh, arms64, "h32l4", 1000)
            # Holm(6): thay hang nay bang p f64, 5 hang kia giu p f32 cua cung ho
            fam = [(t_, s2) for t_ in ("hops", "delay") for s2 in SHELLS[:3]]
            ps32 = [R.pooled_stats(rows32, t_, s2, arms_, "h32l4", 1000)["p_wilcoxon"] for (t_, s2) in fam]
            k = fam.index((task, sh)); ps64 = list(ps32); ps64[k] = q64["p_wilcoxon"]
            h32 = R.holm(ps32)[k]; h64 = R.holm(ps64)[k]
            S32 = [len(set(R.cell(rows32, task, sh, a, "h32l4", 1000).get("heat", {})) & set(R.cell(rows32, task, sh, a, "h32l4", 1000).get("qw", {}))) for a in arms_]
            S64 = [len(set(R.cell(have64, task, sh, a, "h32l4", 1000).get("heat", {})) & set(R.cell(have64, task, sh, a, "h32l4", 1000).get("qw", {}))) for a in arms64]
            lab = "%s %d, %s" % (task, NN[sh], glab)
            T.append("%s & float32 & %d & $%+.4f$ & $[%+.4f,\\,%+.4f]$ & %d:%d & %s & %s & %s \\\\" % (lab, q32["n"], q32["diff"], q32["ci_lo"], q32["ci_hi"], q32["wins_a"], q32["wins_b"], fp(q32["p_wilcoxon"]), fp(h32), "/".join(map(str, S32))))
            T.append("& float64 & %d & $%+.4f$ & $[%+.4f,\\,%+.4f]$ & %d:%d & %s & %s & %s \\\\" % (q64["n"], q64["diff"], q64["ci_lo"], q64["ci_hi"], q64["wins_a"], q64["wins_b"], fp(q64["p_wilcoxon"]), fp(h64), "/".join(map(str, S64))))
            T.append("\\addlinespace[2pt]")
            key_ = "numPsixfour" + tag + task.capitalize() + SHNAME[sh]
            M(key_ + "Wins", "%d:%d" % (q64["wins_a"], q64["wins_b"])); M(key_ + "Holm", fp(h64)); M(key_ + "D", "%+.4f" % q64["diff"]); M(key_ + "Arms", len(arms64)); M(key_ + "N", q64["n"])
            M(key_ + "Survives", "yes" if h64 < 0.05 else "no")
            M(key_ + "SchangeArms", sum(1 for a_, b_ in zip(S32, S64) if a_ != b_))
        T.append("\\bottomrule\n\\end{tabular}"); tabfile("tab-precision-certified.tex", T)
        M("numPsixfourRuns", len(p64))
    M("numHasPsixfour", int(HAS_P64))

    rc = R.load([os.path.join(rev3, "randomcut_*.csv")]) if os.path.isdir(rev3) else []
    HAS_RC = any(r["op"] == "qw" for r in rc)
    if HAS_RC:
        arms_rc = sorted({r["arm"] for r in rc if r["op"] in ("heat", "qw")}, key=lambda a: ARMS.index(a))
        T = ["\\begin{tabular}{@{}lrrllllcrr@{}}\n\\toprule\ngraph & $t$ arm & const & GCN & heat & walk & leader & heat:walk & $p_{\\mathrm{W}}$ & gain \\\\\n\\midrule"]
        for glab, rows_ in (("torus", g3), ("seam cut", sc), ("random cut", rc)):
            arms_ = [a for a in ARMS if any(r["arm"] == a and r["op"] == "qw" and (r["task"], r["shell"]) == ("hops", "s1584") for r in rows_)]
            for a in arms_:
                c = R.cell(rows_, "hops", "s1584", a, "h32l4", 1000); st, cm, gain, vd, ld = R.summarise(c); ps = R.paired_stats(c)
                T.append("%s & %s & %.3f & %s & %s & %s & %s & %d:%d & %s & %.0f\\%% \\\\" % (glab if a == arms_[0] else "", arm_label(a), cm, pm(st, "gcn"), pm(st, "heat"), pm(st, "qw"), ld, ps["wins_a"], ps["wins_b"], fp(ps["p_wilcoxon"]), 100 * gain))
            q = R.pooled_stats(rows_, "hops", "s1584", arms_, "h32l4", 1000)
            T.append("\\multicolumn{10}{@{}l}{\\quad pooled over %d arms: $\\bar d=%+.4f$ $[%+.4f,\\,%+.4f]$, %d:%d, Wilcoxon $p=%s$, MDE %s} \\\\\\addlinespace[2pt]" % (len(arms_), q["diff"], q["ci_lo"], q["ci_hi"], q["wins_a"], q["wins_b"], fp(q["p_wilcoxon"]), fm(R.mde_wilcoxon(q["sd"], q["n"], 0.05))))
            key_ = "numRcut" + glab.replace(" ", "").capitalize()
            M(key_ + "Wins", "%d:%d" % (q["wins_a"], q["wins_b"])); M(key_ + "PW", fp(q["p_wilcoxon"])); M(key_ + "D", "%+.4f" % q["diff"]); M(key_ + "Leader", "heat" if q["diff"] < 0 else "walk")
        T.append("\\bottomrule\n\\end{tabular}"); tabfile("tab-randomcut.tex", T)
        M("numRcutRuns", len(rc)); M("numRcutPathology", sum(r["pathology"] for r in rc if r["op"] in CORE))
        gp = [abs(np.mean([r["train_mae"] for r in c.get(op, {}).values()]) - np.mean([r["mae"] for r in c.get(op, {}).values()])) for a in arms_rc for c in [R.cell(rc, "hops", "s1584", a, "h32l4", 1000)] for op in CORE if c.get(op)]
        M("numRcutFitMaxGap", "%.3f" % max(gp))
    M("numHasRcut", int(HAS_RC))

    sg1 = R.load([os.path.join(rev3, "seamcut_grid1_*.csv")]) if os.path.isdir(rev3) else []
    HAS_SG1 = any(r["op"] == "qw" and r["shell"] == "s4400" for r in sg1)
    if HAS_SG1:
        arms_g1 = sorted({r["arm"] for r in sg1 if r["op"] in ("heat", "qw")}, key=lambda a: ARMS.index(a))
        T = ["\\begin{tabular}{@{}lrrrrcrrrr@{}}\n\\toprule\n& \\multicolumn{4}{c}{hop field} & & \\multicolumn{4}{c}{delay field} \\\\\n\\cmidrule{2-5}\\cmidrule{7-10}\n$t$ arm & 264 & 1584 & 3168 & 4400 & & 264 & 1584 & 3168 & 4400 \\\\\n\\midrule"]
        gbig = []
        for arm in arms_g1:
            parts = []
            for task in ("hops", "delay"):
                cells_ = [R.summarise(R.cell(sg1, task, sh, arm, "h32l4", 200)) for sh in SHELLS]
                parts.append(" & ".join(("%.1f" % (100 * g)) + ("" if vd != "floor" else "$^{\\dagger}$") for (_, _, g, vd, _) in cells_))
                gbig += [100 * cells_[i][2] for i in (1, 2, 3)]
            T.append("%s & %s & & %s \\\\" % (arm_label(arm), parts[0], parts[1]))
        T.append("\\bottomrule\n\\end{tabular}"); tabfile("tab-seam-floor.tex", T)
        M("numSeamGridOneRuns", len(sg1)); M("numSeamGridOneArms", len(arms_g1)); M("numSeamGainLargeMax", round(max(gbig), 1))
        M("numSeamGridOneFloorLarge", sum(1 for arm in arms_g1 for task in ("hops", "delay") for sh in SHELLS[1:] if R.summarise(R.cell(sg1, task, sh, arm, "h32l4", 200))[3] == "floor"))
        M("numSeamGridOneLargeCells", len(arms_g1) * 6)
    M("numHasSeamGridOne", int(HAS_SG1))


    pr = R.load([os.path.join(rev2, "precision_*.csv")]) if os.path.isdir(rev2) else []
    HAS_PREC = any(r["op"] == "qw" for r in pr)
    if HAS_PREC:
        T = ["\\begin{tabular}{@{}lrrrr@{}}\n\\toprule\noperator & seeds & MAE float32 & MAE float64 & max $|\\Delta|$ over seeds \\\\\n\\midrule"]
        c32 = R.cell(g3, "hops", "s1584", "softplus/t0=0.5", "h32l4", 1000, include_pathology=True)
        c64 = R.cell(pr, "hops", "s1584", "softplus/t0=0.5", "h32l4", 1000, include_pathology=True)
        dmax_all = 0.0
        for op in CORE:
            common = sorted(set(c32.get(op, {})) & set(c64.get(op, {})))
            a = np.array([c32[op][s_]["mae"] for s_ in common]); b = np.array([c64[op][s_]["mae"] for s_ in common])
            ok = np.isfinite(a) & np.isfinite(b)
            dm = float(np.max(np.abs(a[ok] - b[ok]))) if ok.any() else float("nan"); dmax_all = max(dmax_all, dm)
            T.append("%s & %d & %.4f & %.4f & %.4f \\\\" % (OPN[op], ok.sum(), a[ok].mean(), b[ok].mean(), dm))
            M("numPrec" + OPN[op].capitalize() + "Delta", "%.4f" % dm)
        T.append("\\bottomrule\n\\end{tabular}"); tabfile("tab-precision.tex", T)
        M("numPrecMaxDelta", "%.4f" % dmax_all)
        # so voi hieu heat-walk cua o do
        ps32 = R.paired_stats(R.cell(g3, "hops", "s1584", "softplus/t0=0.5", "h32l4", 1000)); ps64 = R.paired_stats(R.cell(pr, "hops", "s1584", "softplus/t0=0.5", "h32l4", 1000))
        M("numPrecSThirtyTwo", ps32["n"]); M("numPrecSSixtyFour", ps64["n"])
        M("numPrecDiffThirtyTwo", "%+.4f" % ps32["diff"]); M("numPrecDiffSixtyFour", "%+.4f" % ps64["diff"]); M("numPrecWinsSixtyFour", "%d:%d" % (ps64["wins_a"], ps64["wins_b"]))
        M("numPrecPathologySixtyFour", sum(r["pathology"] for r in pr)); M("numPrecPathologyThirtyTwo", sum(r["pathology"] for r in g3 if (r["task"], r["shell"], r["arm"], r["cfg"]) == ("hops", "s1584", "softplus/t0=0.5", "h32l4") and r["op"] in CORE))
    M("numHasPrecision", int(HAS_PREC)); M("numPrecRuns", len(pr))
    M("numRevTwoRuns", len(lad) + len(sc) + len(pr))

# ================================================================ chi phi
T = ["\\begin{tabular}{@{}lrrrcrrr@{}}\n\\toprule\n& \\multicolumn{3}{c}{200 epochs} & & \\multicolumn{3}{c}{1000 epochs} \\\\\n\\cmidrule{2-4}\\cmidrule{6-8}\n$N$ & GCN & heat & walk & & GCN & heat & walk \\\\\n\\midrule"]
def secs(rows, sh, op, ep, cfg="h32l4"):
    v = [float(r["secs"]) for r in rows if r["shell"] == sh and r["op"] == op and r["epochs"] == str(ep) and r["cfg"] == cfg]
    return np.median(v) if v else np.nan
for sh in SHELLS:
    a = [secs(g12, sh, op, 200) for op in CORE]; b = [secs(g3, sh, op, 1000) for op in CORE] if g3 else [np.nan] * 3
    T.append("%d & %s & & %s \\\\" % (NN[sh], " & ".join("%.0f" % x for x in a), " & ".join(("%.0f" % x) if x == x else "---" for x in b)))
T.append("\\bottomrule\n\\end{tabular}"); tabfile("tab8-cost.tex", T)
M("numSecsWalkLarge", "%.0f" % secs(g12, "s4400", "qw", 200)); M("numSecsGcnLarge", "%.0f" % secs(g12, "s4400", "gcn", 200)); M("numSecsHeatLarge", "%.0f" % secs(g12, "s4400", "heat", 200))
M("numFeasibleNGpuMem", int(np.sqrt(24e9 / (4 * 4 * 4))) // 100 * 100)   # 24 GB, ~4 ma tran N^2 float32, du 4x

# ================================================================ minh hoa giai tich
# (Accelerate BLAS tren macOS in canh bao 'divide by zero in matmul' gia; ket qua huu han, assert ben duoi)
np.seterr(all="ignore")
n = 401; A = np.zeros((n, n)); idx = np.arange(n - 1); A[idx, idx + 1] = A[idx + 1, idx] = 1
Lp = np.diag(A.sum(1)) - A; w, U = np.linalg.eigh(Lp); c0 = n // 2; pos = np.arange(n) - c0
fig, axes = plt.subplots(1, 2, figsize=(W_WIDE, 2.8))
for ti, tt in enumerate((5, 20)):
    for op in ("heat", "qw"):
        row = (U * np.exp(-tt * w)) @ U[c0] if op == "heat" else np.abs((U * np.exp(-1j * tt * w)) @ U[c0]) ** 2
        row = row / row.sum()
        axes[0].plot(pos, row, color=C[op], ls=LS[op], lw=1.0, alpha=0.5 + 0.5 * ti, label=("%s, $t$=%d" % ("heat" if op == "heat" else "walk", tt)))
axes[0].set_xlim(-80, 80); axes[0].set_xlabel("distance from source (hops)"); axes[0].set_ylabel("row of $\\Phi$ (normalised)"); axes[0].legend(fontsize=6.5)
ts = np.linspace(0.5, 40, 60); var = {"heat": [], "qw": []}
for tt in ts:
    for op in ("heat", "qw"):
        row = (U * np.exp(-tt * w)) @ U[c0] if op == "heat" else np.abs((U * np.exp(-1j * tt * w)) @ U[c0]) ** 2
        row = row / row.sum(); mu = (row * pos).sum(); var[op].append(float((row * (pos - mu) ** 2).sum()))
assert all(np.isfinite(var[op]).all() for op in var), "phuong sai khong huu han"
np.seterr(all="warn")
for op in ("heat", "qw"):
    axes[1].plot(ts, var[op], color=C[op], ls=LS[op], label=LBL[op])
axes[1].set_xlabel("propagation time $t$"); axes[1].set_ylabel("spatial variance of the row"); axes[1].set_yscale("log"); axes[1].set_xscale("log"); axes[1].legend(fontsize=7)
fig.subplots_adjust(wspace=0.38)
save(fig, "fig5-spreading")
FIT_LO = 10
M("numSpreadFitTmin", "%.0f" % ts[FIT_LO]); M("numSpreadFitTmax", "%.0f" % ts[-1])
for op in ("heat", "qw"):
    x, y = np.log(ts[FIT_LO:]), np.log(var[op][FIT_LO:]); a, b = np.polyfit(x, y, 1)
    M("numSpreadExp" + ("Heat" if op == "heat" else "Walk"), "%.2f" % a); M("numSpreadResid" + ("Heat" if op == "heat" else "Walk"), "%.3f" % np.sqrt(np.mean((y - (a * x + b)) ** 2)))

# ================================================================ so do giao thuc (TikZ)
shells_txt = " $\\cdot$ ".join(str(_SH[k][0]) for k in SHELLS)
proto = r"""\begin{tikzpicture}[
  font=\scriptsize, >={Stealth[length=1.8mm]},
  grp/.style={draw, rounded corners=1.5pt, inner sep=4pt, align=left, text width=46mm, minimum height=23mm, fill=black!3, anchor=north west},
  grid/.style={draw, rounded corners=1.5pt, inner sep=3pt, align=left, text width=38mm, minimum height=15mm, fill=black!8, anchor=north west},
  rule/.style={draw, rounded corners=1.5pt, inner sep=2.5pt, align=center, text width=21.5mm, minimum height=12mm, fill=black!12, anchor=north west},
  lab/.style={font=\scriptsize\itshape, text=black!70, align=center}]
% --- tang 1: thiet ke
\node[grp] (g1) at (0,0) {\textbf{Graphs and tasks}\\[1pt]
  Walker-delta shells of SHELLS satellites, +Grid links; torus in the main grids, seam cut as an arm\\
  tasks: hop field $\cdot$ delay field\\
  10 seeds; per seed 8 training and 6 evaluation instances};
\node[grp] (g2) at ([xshift=4mm]g1.north east) {\textbf{Operators: one eigenbasis, one network}\\[1pt]
  GCN step, one hop per layer\\
  heat $e^{-t\mathbf{L}}$ and walk $|e^{-it\mathbf{L}}|^{2}$, learned $t$ per layer\\
  fixed-reach baselines without $t$: PPR ($\alpha$), SGC ($K'$)\\
  reach of every operator measured on the graph};
\node[grp] (g3) at ([xshift=4mm]g2.north east) {\textbf{Arms}\\[1pt]
  $t$ mapping: relu $\cdot$ softplus\\
  $t$ initialisation: $t_{0}=0.5 \cdot 2$\\
  capacity: PREL $\cdot$ PSUB parameters\\
  budget: 200 $\cdot$ 1000 epochs\\
  graph: torus $\cdot$ seam cut};
% --- tang 2: cac luoi
\node[grid] (q1) at ([yshift=-6mm]g1.south west) {\textbf{Grid 1}, 200 epochs\\4 shells, 2 capacities, 4 arms\\NRUNSA runs + NFIXA baseline};
\node[grid] (q2) at ([xshift=2mm]q1.north east) {\textbf{Grid 2}, 1000 epochs\\3 shells, width 32, 4 arms\\NRUNSB runs + NFIXB baseline + NLAD ladder};
\node[grid] (q3) at ([xshift=2mm]q2.north east) {\textbf{Seam-cut arm}\\grid 2 repeated on the seam-cut graph\\NSEAM runs};
\node[grid] (q4) at ([xshift=2mm]q3.north east) {\textbf{Precision check}\\one cell of grid 2, double precision\\NPREC runs};
% --- tang 3: luat doc
\node[rule] (r1) at ([yshift=-6mm]q1.south west) {1. constant\\baseline,\\every metric};
\node[rule] (r2) at ([xshift=2.5mm]r1.north east) {2. pathology\\excluded\\and counted};
\node[rule] (r3) at ([xshift=2.5mm]r2.north east) {3. floor\\$g<0.05$:\\not rankable};
\node[rule] (r4) at ([xshift=2.5mm]r3.north east) {4. seed vote\\$\geq 7/10$\\in a cell};
\node[rule] (r5) at ([xshift=2.5mm]r4.north east) {5. robust\\same in\\every arm};
\node[rule, fill=black!22] (r6) at ([xshift=2.5mm]r5.north east) {6. inference\\pooled test,\\Holm, MDE};
\draw[->] (r1) -- (r2); \draw[->] (r2) -- (r3); \draw[->] (r3) -- (r4); \draw[->] (r4) -- (r5); \draw[->] (r5) -- (r6);
% nhom vai tro
\draw[black!60] ([yshift=-1.5mm]r1.south west) -- ([yshift=-1.5mm]r3.south east);
\node[lab, anchor=north] at ([yshift=-2mm]$(r1.south west)!0.5!(r3.south east)$) {filters, applied to every cell};
\draw[black!60] ([yshift=-1.5mm]r4.south west) -- ([yshift=-1.5mm]r5.south east);
\node[lab, anchor=north] at ([yshift=-2mm]$(r4.south west)!0.5!(r5.south east)$) {descriptive; 34\% null false positives};
\draw[black!60] ([yshift=-1.5mm]r6.south west) -- ([yshift=-1.5mm]r6.south east);
\node[lab, anchor=north, text width=21mm] at ([yshift=-2mm]r6.south) {what the paper\\stands on};
% mui ten giua cac tang
\draw[->] (g2.south) -- ([yshift=0.3mm]q2.north -| g2.south);
\coordinate (rc) at ($(r3.north east)!0.5!(r4.north west)$);
\draw[->] (q2.south east -| rc) -- ([yshift=0.5mm]rc);
\end{tikzpicture}
"""
proto = (proto.replace("SHELLS", shells_txt).replace("PREL", str(NUM["numReleasedParams"])).replace("PSUB", str(NUM["numSubmittedParams"]))
         .replace("NRUNSA", str(NUM["numGridTwelveRuns"])).replace("NFIXA", str(NUM["numFixedRunsTwelve"]))
         .replace("NRUNSB", str(NUM["numGridThreeRuns"])).replace("NFIXB", str(NUM["numFixedRunsThree"]))
         .replace("NLAD", str(NUM.get("numLadderRuns", 0))).replace("NSEAM", str(NUM.get("numSeamRuns", 0))).replace("NPREC", str(NUM.get("numPrecRuns", 0))))
io.open(os.path.join(OUTD, "fig-protocol.tex"), "w").write("% GENERATED by figures/make_figures.py\n" + proto)

# ================================================================ bang tom tat headline
if g3:
    T = ["\\begin{tabular}{@{}p{0.50\\textwidth}p{0.24\\textwidth}p{0.2\\textwidth}@{}}\n\\toprule\nfinding & value & derived in \\\\\n\\midrule",
         "runs, fixed 200-epoch budget (grid 1) & %d & Sec.~\\ref{sec:floor} \\\\" % NUM["numGridTwelveRuns"],
         "largest gain over constant on any shell $\\geq$1584, any arm, either capacity (grid 1) & %s\\%% & Fig.~\\ref{fig:floor}, Tab.~\\ref{tab:floor} \\\\" % NUM["numGainLargeMax"],
         "rankable cells at $\\geq$1584 satellites, hop field, at floor 5\\%% / 2\\%% / 1\\%% (grid 1) & %d / %d / %d of 24 & Tab.~\\ref{tab:sens} \\\\" % (NUM["numRankableLargeAtGFive"], NUM["numRankableLargeAtGTwo"], NUM["numRankableLargeAtGOne"]),
         "heat-vs-walk verdicts at 264 satellites across the four $t$ arms, submitted capacity (grid 1) & %s & Fig.~\\ref{fig:arms} \\\\" % NUM["numSTwoSixFourVerdictsSubmitted"],
         "the same, released capacity (grid 1) & %s & Tab.~\\ref{tab:s264} \\\\" % NUM["numSTwoSixFourVerdictsReleased"],
         "runs, 1000-epoch budget, %d $t$ arms (grid 2) & %d & Sec.~\\ref{sec:budget} \\\\" % (len(ARMS3), NUM["numGridThreeRuns"]),
         "task-scale cells where heat / walk wins in every arm, MAE (grid 2) & %d / %d of 6 & Tab.~\\ref{tab:grid3} \\\\" % (NUM["numGthreeHeatRobust"], NUM["numGthreeWalkRobust"]),
         "the same on the far-node metric (grid 2) & %d / %d of 6 & Tab.~\\ref{tab:aurc} \\\\" % (NUM["numAurcHeatRobust"], NUM["numAurcWalkRobust"]),
         "arm-level cells where heat / walk leads in mean, MAE (grid 2) & %d / %d of %d & Tab.~\\ref{tab:grid3} \\\\" % (NUM["numGthreeLeadHeat"], NUM["numGthreeLeadWalk"], NUM["numGthreeArmCells"]),
         "arm-level cells with Wilcoxon $p<0.05$ before / after Holm, MAE (grid 2) & %d / %d of %d & Tab.~\\ref{tab:grid3inf} \\\\" % (NUM["numGthreeSigRaw"], NUM["numGthreeSigHolm"], NUM["numGthreeArmCells"]),
         "arm-level cells whose 95\\%% CI excludes zero, favouring heat / walk, MAE (grid 2) & %d / %d of %d & Tab.~\\ref{tab:grid3inf} \\\\" % (NUM["numCIExclZeroHeat"], NUM["numCIExclZeroWalk"], NUM["numGthreeArmCells"]),
         "arm-level cells that can reject after Holm at any effect size (grid 2) & %d of %d & Tab.~\\ref{tab:power} \\\\" % (NUM["numPowerNeedSweep"], NUM["numGthreeArmCells"]),
         "pooled (task, shell) tests significant after Holm over 6, MAE; direction & %d of 6; heat 264 & Tab.~\\ref{tab:pooled} \\\\" % NUM["numPooledSigHolm"],
         "the same on the seam-cut graph & %d of 6; heat 264, walk 1584 hop & Tab.~\\ref{tab:seampooled} \\\\" % NUM["numSeamPooledSigHolm"] if NUM.get("numHasSeam") else "",
         "best spectral kernel vs best fixed-reach baseline of the ladder, hop field, 1584: best / worst $t$ arm & %s\\%% / %s\\%% & Tab.~\\ref{tab:ladder} \\\\" % (NUM["numLadderGapBestPctHopsShellOne"], NUM["numLadderGapWorstPctHopsShellOne"]) if NUM.get("numHasLadder") else "",
         "runs collapsing to the constant solution under long training (grid 2) & %d (%s\\%%) & Sec.~\\ref{sec:collapse} \\\\" % (NUM["numGridThreePathology"], NUM["numGridThreePathologyPct"]),
         "preliminary 1584-satellite result, walk vs heat, %d seeds & %s vs %s & Sec.~\\ref{sec:budget} \\\\" % (NUM["numPrelimSeeds"], NUM["numPrelimWalkMAE"], NUM["numPrelimHeatMAE"]),
         "\\bottomrule\n\\end{tabular}"]
    tabfile("tab-summary.tex", T)

with io.open(os.path.join(OUTD, "numbers.tex"), "w", encoding="utf-8") as fh:
    fh.write("% GENERATED by figures/make_figures.py. Do not edit.\n")
    for k, v in sorted(NUM.items()):
        fh.write("\\newcommand{\\%s}{%s}\n" % (k, v))
print("  %d macro -> figures/out/numbers.tex" % len(NUM))
